
package packageGUI;
import java.awt.BorderLayout;
import java.awt.Desktop;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.net.URI;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import java.awt.Container;



public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
           initComponents();
           postInit();//διευκολύνει διότι δεν είναι δεσμευτικός απο τα components του 
                      //Swing Pallete
}
    
    
    /**
     * μετά την εκτέλεση - ολοκλήρωση των δοκιμών αφαιρούμε την main
     * public static void main(String args[])  
     * Η εφαρμογή Εκκινείται από την 
     * App.java του package packageMain
     * 
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * δεσμευτικός από την σχεδίαση του Swing
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        tabsMain = new javax.swing.JTabbedPane();
        tabSearch = new javax.swing.JPanel();
        tabSaved = new javax.swing.JPanel();
        tabStats = new javax.swing.JPanel();
        mainMenuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        miClearSearch = new javax.swing.JMenuItem();
        menuSaved = new javax.swing.JMenu();
        miOpenSavedTab = new javax.swing.JMenuItem();
        menuStats = new javax.swing.JMenu();
        miOpenStatsTab = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenu();
        miExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Καρτέλα Επιλογών WiKi");

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1171, Short.MAX_VALUE)
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        getContentPane().add(pnlTop, java.awt.BorderLayout.PAGE_START);

        tabsMain.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout tabSearchLayout = new javax.swing.GroupLayout(tabSearch);
        tabSearch.setLayout(tabSearchLayout);
        tabSearchLayout.setHorizontalGroup(
            tabSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1171, Short.MAX_VALUE)
        );
        tabSearchLayout.setVerticalGroup(
            tabSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        tabsMain.addTab("Search Articles", tabSearch);
        tabSearch.getAccessibleContext().setAccessibleName("tabSearch");

        javax.swing.GroupLayout tabSavedLayout = new javax.swing.GroupLayout(tabSaved);
        tabSaved.setLayout(tabSavedLayout);
        tabSavedLayout.setHorizontalGroup(
            tabSavedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1171, Short.MAX_VALUE)
        );
        tabSavedLayout.setVerticalGroup(
            tabSavedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        tabsMain.addTab("Saved Articles", tabSaved);
        tabSaved.getAccessibleContext().setAccessibleName("tabSaved");
        tabSaved.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout tabStatsLayout = new javax.swing.GroupLayout(tabStats);
        tabStats.setLayout(tabStatsLayout);
        tabStatsLayout.setHorizontalGroup(
            tabStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1171, Short.MAX_VALUE)
        );
        tabStatsLayout.setVerticalGroup(
            tabStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        tabsMain.addTab("Stats & Keywords", tabStats);
        tabStats.getAccessibleContext().setAccessibleName("tabStats");

        getContentPane().add(tabsMain, java.awt.BorderLayout.CENTER);
        tabsMain.getAccessibleContext().setAccessibleName("tabsMain");
        tabsMain.getAccessibleContext().setAccessibleDescription("");

        mainMenuBar.setToolTipText("");
        mainMenuBar.setName("Καρτέλα Επιλογών WiKi"); // NOI18N

        menuFile.setText("File");
        menuFile.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        miClearSearch.setText("Clear Search");
        miClearSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClearSearchActionPerformed(evt);
            }
        });
        menuFile.add(miClearSearch);
        miClearSearch.getAccessibleContext().setAccessibleName("miClearSearch");
        miClearSearch.getAccessibleContext().setAccessibleDescription("");

        mainMenuBar.add(menuFile);
        menuFile.getAccessibleContext().setAccessibleName("menuFile");

        menuSaved.setText("Saved");
        menuSaved.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        miOpenSavedTab.setText("Saved Articles");
        menuSaved.add(miOpenSavedTab);
        miOpenSavedTab.getAccessibleContext().setAccessibleName("miOpenSavedTab");

        mainMenuBar.add(menuSaved);
        menuSaved.getAccessibleContext().setAccessibleName("menuSaved");

        menuStats.setText("Stats");
        menuStats.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        miOpenStatsTab.setText("Statistics");
        menuStats.add(miOpenStatsTab);
        miOpenStatsTab.getAccessibleContext().setAccessibleName("miOpenStatsTab");

        mainMenuBar.add(menuStats);
        menuStats.getAccessibleContext().setAccessibleName("menuStats");

        menuExit.setText("Exit");
        menuExit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        menuExit.add(miExit);
        miExit.getAccessibleContext().setAccessibleName("miExit");
        miExit.getAccessibleContext().setAccessibleDescription("");

        mainMenuBar.add(menuExit);
        menuExit.getAccessibleContext().setAccessibleName("menuExit");

        setJMenuBar(mainMenuBar);
        mainMenuBar.getAccessibleContext().setAccessibleName("mainMenuBar");

        pack();
    }// </editor-fold>//GEN-END:initComponents


  //Ο κωδικας δεν είναι δέσμιος από την σχεδίαση του SWing
  //Τροποποιείται πίο εύκολα
 
// ====== UI fields (built in postInit) ======
private JTextField txtKeywords;
private JButton btnSearch, btnClear, btnViewDetails, btnSave, btnOpenInBrowser;
private JRadioButton rbDbOnly, rbDbApi;
private ButtonGroup bgSearchMode;

private JTable tblResults;
private JTextArea txtPreview;

private JLabel lblStatus;
private JProgressBar progress;
private JTable tblSaved;
private JTextArea txtSavedPreview;
private JButton btnLoadArticle, btnDeleteSaved, btnClearList;
private JLabel lblSavedCount;

// ==============================
// postInit(): Εικόνα 1 + 1.1/1.2/1.3
// ==============================
private void postInit() {
    buildTopWrapper();   // Εικόνα 1: Keywords/Search/Clear + mode
    buildSearchTabUI();  // Εικόνα 1: Results + Preview + buttons
    buildSavedTabUI();  // Εικόνα 2: Saved Articles

    buildStatusBar();    // Εικόνα 1: lblStatus κάτω δεξιά

    wireMenuNavigation();

    setStatus("Ready", false);
    tabsMain.setSelectedComponent(tabSearch);

    // ---- Window size + center (≈ μισή οθόνη 24") ----
    java.awt.Dimension screen = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    int w = (int) (screen.width * 0.80);
    int h = (int) (screen.height * 0.75);
    setSize(w, h);
    setLocationRelativeTo(null); // κέντρο οθόνης
    setMinimumSize(new java.awt.Dimension(900,600)); // προαιρετικό
}


private void buildTopWrapper() {
    // Panel με controls (αριστερά)
    JPanel topControls = new JPanel(new FlowLayout(FlowLayout.LEFT, 8, 8));

    JLabel lbl = new JLabel("Keywords");
    lbl.setFont(new java.awt.Font("Arial", 0, 14));

    txtKeywords = new JTextField(28);
    txtKeywords.setFont(new java.awt.Font("Arial", 0, 14));

    btnSearch = new JButton("Search");
    btnSearch.setFont(new java.awt.Font("Arial", 0, 14));

    btnClear = new JButton("Clear");
    btnClear.setFont(new java.awt.Font("Arial", 0, 14));

    rbDbOnly = new JRadioButton("DB only");
    rbDbOnly.setFont(new java.awt.Font("Arial", 0, 14));
    rbDbOnly.setActionCommand("DB_ONLY");

    rbDbApi = new JRadioButton("DB/API");
    rbDbApi.setFont(new java.awt.Font("Arial", 0, 14));
    rbDbApi.setActionCommand("DB_API");

    bgSearchMode = new ButtonGroup();
    bgSearchMode.add(rbDbOnly);
    bgSearchMode.add(rbDbApi);
    rbDbApi.setSelected(true);

    topControls.add(lbl);
    topControls.add(txtKeywords);
    topControls.add(btnSearch);
    topControls.add(btnClear);
    topControls.add(rbDbOnly);
    topControls.add(rbDbApi);

    // Wrapper (για να ΜΗΝ πειράξουμε το GroupLayout του pnlTop)
    JPanel pnlTopWrapper = new JPanel(new BorderLayout());
    pnlTopWrapper.add(pnlTop, BorderLayout.CENTER);     // το generated panel μένει
    pnlTopWrapper.add(topControls, BorderLayout.WEST);  // τα controls “κάθονται” πάνω

    // Αντικατάσταση στο PAGE_START
    Container content = getContentPane();
    content.remove(pnlTop);
    content.add(pnlTopWrapper, BorderLayout.PAGE_START);

    // Handlers
    btnSearch.addActionListener(e -> onSearch());
    txtKeywords.addActionListener(e -> onSearch());
    btnClear.addActionListener(e -> clearSearchUI());

    content.revalidate();
    content.repaint();
}

private void buildSearchTabUI() {
    tabSearch.removeAll();
    tabSearch.setLayout(new BorderLayout());

    // Results table (αριστερά)
    DefaultTableModel model = new DefaultTableModel(
            new Object[][]{
                    {"Java (programming language)", "DB", 12345L},
                    {"JavaScript", "API", 23456L},
                    {"Swing (Java)", "DB", 34567L}
            },
            new String[]{"Title", "Source", "PageId"}
    ) {
        @Override public boolean isCellEditable(int r, int c) { return false; }
    };

    tblResults = new JTable(model);
    tblResults.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    // Κρύβουμε PageId στήλη (μένει το data)
    tblResults.getColumnModel().getColumn(2).setMinWidth(0);
    tblResults.getColumnModel().getColumn(2).setMaxWidth(0);
    tblResults.getColumnModel().getColumn(2).setPreferredWidth(0);

    JScrollPane spResults = new JScrollPane(tblResults);

    // Preview (δεξιά)
    txtPreview = new JTextArea();
    txtPreview.setEditable(false);
    txtPreview.setLineWrap(true);
    txtPreview.setWrapStyleWord(true);
    txtPreview.setText("Preview εμφανίζεται εδώ όταν επιλέξεις αποτέλεσμα…");
    JScrollPane spPreview = new JScrollPane(txtPreview);

    JSplitPane split = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, spResults, spPreview);
    split.setResizeWeight(0.45);

    // Buttons κάτω (View Details / Save / Open in Browser)
    JPanel pnlButtons = new JPanel(new FlowLayout(FlowLayout.LEFT, 10, 8));
    btnViewDetails = new JButton("View Details");
    btnSave = new JButton("Save");
    btnOpenInBrowser = new JButton("Open in Browser");

    pnlButtons.add(btnViewDetails);
    pnlButtons.add(btnSave);
    pnlButtons.add(btnOpenInBrowser);

    tabSearch.add(split, BorderLayout.CENTER);
    tabSearch.add(pnlButtons, BorderLayout.SOUTH);

    // Selection -> preview
    tblResults.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
        if (!e.getValueIsAdjusting()) updatePreviewFromSelection();
    });

    // Εικόνα 1.1 / 1.2 / 1.3
    btnViewDetails.addActionListener(e -> showDetailsDialog());
    btnSave.addActionListener(e -> showSaveConfirm());
    btnOpenInBrowser.addActionListener(e -> openInBrowser());

    tabSearch.revalidate();
    tabSearch.repaint();
}
// ΣΤΟ postInit() ΘΥΜΙΖΩ ότι πρέπει να κληθεί:
// buildSavedTabUI();  // Εικόνα 2: Saved Articles


private void buildSavedTabUI() {
    tabSaved.removeAll();
    tabSaved.setLayout(new BorderLayout(10, 10));

    // ===== Left: Full Table =====
    DefaultTableModel savedModel = new DefaultTableModel(
            new Object[][]{
                    // Title, PageId, SavedAt, Source
                    {"Concurrency (computer science)", 11223L, "2026-02-07 10:12", "DB"},
                    {"Machine learning",              22345L, "2026-02-07 10:01", "DB"},
                    {"Python (programming language)", 23465L, "2026-02-06 18:45", "API"},
                    {"Big data",                      34567L, "2026-02-06 17:55", "DB"},
                    {"Artificial intelligence",       45678L, "2026-02-05 15:33", "DB"},
                    {"Natural language processing",   56789L, "2026-02-05 14:10", "DB"}
            },
            new String[]{"Title", "PageId", "Saved At", "Source"}
    ) {
        @Override public boolean isCellEditable(int r, int c) { return false; }
        @Override public Class<?> getColumnClass(int col) {
            return switch (col) {
                case 1 -> Long.class;   // PageId
                default -> String.class;
            };
        }
    };

    tblSaved = new JTable(savedModel);
    tblSaved.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    tblSaved.setAutoCreateRowSorter(true);
    JScrollPane spSavedTable = new JScrollPane(tblSaved);

    // ===== Right: Preview =====
    txtSavedPreview = new JTextArea();
    txtSavedPreview.setEditable(false);
    txtSavedPreview.setLineWrap(true);
    txtSavedPreview.setWrapStyleWord(true);
    txtSavedPreview.setText("Title:\n\nPreview κειμένου\n(placeholder)…");
    JScrollPane spSavedPreview = new JScrollPane(txtSavedPreview);

    JSplitPane split = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, spSavedTable, spSavedPreview);
    split.setResizeWeight(0.72); // πιο μεγάλο table (εικόνα 2)

    // ===== Bottom: buttons + count =====
    JPanel pnlBottom = new JPanel(new BorderLayout());

    JPanel pnlButtons = new JPanel(new FlowLayout(FlowLayout.LEFT, 10, 8));
    btnLoadArticle = new JButton("Load Article");
    btnDeleteSaved = new JButton("Delete");
    btnClearList   = new JButton("Clear List");
    pnlButtons.add(btnLoadArticle);
    pnlButtons.add(btnDeleteSaved);
    pnlButtons.add(btnClearList);

    lblSavedCount = new JLabel();
    lblSavedCount.setFont(new java.awt.Font("Arial", 0, 12));
    updateSavedCountLabel();

    JPanel pnlCount = new JPanel(new FlowLayout(FlowLayout.RIGHT, 10, 8));
    pnlCount.add(lblSavedCount);

    pnlBottom.add(pnlButtons, BorderLayout.WEST);
    pnlBottom.add(pnlCount, BorderLayout.EAST);

    // ===== Assemble tab =====
    tabSaved.add(split, BorderLayout.CENTER);
    tabSaved.add(pnlBottom, BorderLayout.SOUTH);

    // ===== Behaviors =====
    tblSaved.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
        if (!e.getValueIsAdjusting()) updateSavedPreviewFromSelection();
    });

    btnLoadArticle.addActionListener(e -> showLoadArticleDialog());     // Εικόνα 2.1
    btnDeleteSaved.addActionListener(e -> deleteSelectedSavedRow());    // Delete
    btnClearList.addActionListener(e -> clearSavedList());             // Clear List

    tabSaved.revalidate();
    tabSaved.repaint();
}

private void updateSavedPreviewFromSelection() {
    int rowView = tblSaved.getSelectedRow();
    if (rowView < 0) return;

    int row = tblSaved.convertRowIndexToModel(rowView);

    String title  = String.valueOf(tblSaved.getModel().getValueAt(row, 0));
    Object pageId = tblSaved.getModel().getValueAt(row, 1);
    String savedAt = String.valueOf(tblSaved.getModel().getValueAt(row, 2));
    String source  = String.valueOf(tblSaved.getModel().getValueAt(row, 3));

    txtSavedPreview.setText(
            "Title: " + title + "\n" +
            "PageId: " + pageId + "\n" +
            "Saved At: " + savedAt + "\n" +
            "Source: " + source + "\n\n" +
            "Preview κειμένου (placeholder)…"
    );

    setStatus("Saved selected: " + title, false);
}

private String getSelectedSavedTitleOrWarn() {
    int rowView = tblSaved.getSelectedRow();
    if (rowView < 0) {
        JOptionPane.showMessageDialog(this, "Select a saved article first.",
                "No selection", JOptionPane.WARNING_MESSAGE);
        setStatus("No saved selection", false);
        return null;
    }
    int row = tblSaved.convertRowIndexToModel(rowView);
    return String.valueOf(tblSaved.getModel().getValueAt(row, 0));
}

private Long getSelectedSavedPageIdOrNull() {
    int rowView = tblSaved.getSelectedRow();
    if (rowView < 0) return null;
    int row = tblSaved.convertRowIndexToModel(rowView);
    Object v = tblSaved.getModel().getValueAt(row, 1);
    if (v instanceof Long l) return l;
    try { return Long.valueOf(String.valueOf(v)); } catch (Exception ex) { return null; }
}

// ==============================
// Εικόνα 2.1: Load Article dialog
// ==============================
private void showLoadArticleDialog() {
    String title = getSelectedSavedTitleOrWarn();
    if (title == null) return;

    Long pageId = getSelectedSavedPageIdOrNull();

    JDialog dlg = new JDialog(this, "Load Article", true);
    dlg.setLayout(new BorderLayout(10, 10));

    JLabel lbl = new JLabel(
            "<html><b>Load article from saved list?</b><br><br>" +
            "Title: " + escapeHtml(title) + "<br>" +
            "PageId: " + (pageId == null ? "-" : pageId) + "<br><br>" +
            "This is a demo dialog (placeholder).</html>"
    );

    JPanel center = new JPanel(new BorderLayout());
    center.add(lbl, BorderLayout.CENTER);

    JButton btnClose = new JButton("Close");
    btnClose.addActionListener(e -> dlg.dispose());

    JPanel bottom = new JPanel(new FlowLayout(FlowLayout.RIGHT, 10, 8));
    bottom.add(btnClose);

    dlg.add(center, BorderLayout.CENTER);
    dlg.add(bottom, BorderLayout.SOUTH);

    dlg.setSize(480, 260);
    dlg.setLocationRelativeTo(this);
    dlg.setVisible(true);

    setStatus("Closed Load Article", false);
}

private void deleteSelectedSavedRow() {
    int rowView = tblSaved.getSelectedRow();
    if (rowView < 0) {
        Toolkit.getDefaultToolkit().beep();
        setStatus("No saved selection", false);
        return;
    }

    int row = tblSaved.convertRowIndexToModel(rowView);
    String title = String.valueOf(tblSaved.getModel().getValueAt(row, 0));

    int choice = JOptionPane.showConfirmDialog(
            this,
            "Delete saved article?\n\n" + title,
            "Delete",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );

    if (choice != JOptionPane.YES_OPTION) {
        setStatus("Delete cancelled", false);
        return;
    }

    DefaultTableModel m = (DefaultTableModel) tblSaved.getModel();
    m.removeRow(row);

    txtSavedPreview.setText("Title:\n\nPreview κειμένου\n(placeholder)…");
    updateSavedCountLabel();
    setStatus("Deleted: " + title, false);
}

private void clearSavedList() {
    DefaultTableModel m = (DefaultTableModel) tblSaved.getModel();
    if (m.getRowCount() == 0) {
        setStatus("Saved list already empty", false);
        return;
    }

    int choice = JOptionPane.showConfirmDialog(
            this,
            "Clear the entire saved list?",
            "Clear List",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );

    if (choice != JOptionPane.YES_OPTION) {
        setStatus("Clear cancelled", false);
        return;
    }

    m.setRowCount(0);
    txtSavedPreview.setText("Title:\n\nPreview κειμένου\n(placeholder)…");
    updateSavedCountLabel();
    setStatus("Saved list cleared", false);
}

private void updateSavedCountLabel() {
    int n = (tblSaved == null) ? 0 : ((DefaultTableModel) tblSaved.getModel()).getRowCount();
    lblSavedCount.setText(n + " saved articles  ✓");
}

private String escapeHtml(String s) {
    if (s == null) return "";
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
}


    
    

private void buildStatusBar() {
    JPanel pnlStatus = new JPanel(new BorderLayout());

    progress = new JProgressBar();
    progress.setIndeterminate(true);
    progress.setVisible(false);

    lblStatus = new JLabel("Ready");
    lblStatus.setFont(new java.awt.Font("Arial", 0, 12));

    pnlStatus.add(progress, BorderLayout.WEST);
    pnlStatus.add(lblStatus, BorderLayout.EAST); // κάτω δεξιά

    getContentPane().add(pnlStatus, BorderLayout.PAGE_END);
    getContentPane().revalidate();
    getContentPane().repaint();
}

private void wireMenuNavigation() {
    miOpenSavedTab.addActionListener(e -> tabsMain.setSelectedComponent(tabSaved));
    miOpenStatsTab.addActionListener(e -> tabsMain.setSelectedComponent(tabStats));
}

// -------- behaviors --------
private void onSearch() {
    String q = (txtKeywords.getText() == null) ? "" : txtKeywords.getText().trim();
    if (q.isEmpty()) {
        Toolkit.getDefaultToolkit().beep();
        setStatus("Enter keywords…", false);
        return;
    }
    String mode = (bgSearchMode.getSelection() != null)
            ? bgSearchMode.getSelection().getActionCommand()
            : "DB_API";

    setStatus("Searching… (" + mode + ")", true);

    // Demo: εδώ θα μπει SwingWorker + Controller
    setStatus("Found results for: " + q, false);
}

private void clearSearchUI() {
    txtKeywords.setText("");
    rbDbApi.setSelected(true);
    tblResults.clearSelection();
    txtPreview.setText("Preview εμφανίζεται εδώ όταν επιλέξεις αποτέλεσμα…");
    setStatus("Ready", false);
    txtKeywords.requestFocusInWindow();
}

private void updatePreviewFromSelection() {
    int row = tblResults.getSelectedRow();
    if (row < 0) return;

    String title = String.valueOf(tblResults.getValueAt(row, 0));
    String source = String.valueOf(tblResults.getValueAt(row, 1));

    txtPreview.setText(
            "Title: " + title + "\n" +
            "Source: " + source + "\n\n" +
            "Preview κειμένου (placeholder)…"
    );
    setStatus("Selected: " + title, false);
}

private String getSelectedTitleOrWarn() {
    int row = tblResults.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Select a result first.",
                "No selection", JOptionPane.WARNING_MESSAGE);
        setStatus("No selection", false);
        return null;
    }
    return String.valueOf(tblResults.getValueAt(row, 0));
}

// ==============================
// Εικόνα 1.1: View Details dialog
// ==============================
private void showDetailsDialog() {
    String title = getSelectedTitleOrWarn();
    if (title == null) return;

    JDialog dlg = new JDialog(this, "Article Details", true);
    dlg.setLayout(new BorderLayout());

    JTextArea area = new JTextArea();
    area.setEditable(false);
    area.setLineWrap(true);
    area.setWrapStyleWord(true);
    area.setText(
            "Article: " + title + "\n\n" +
            "Details content (placeholder)…\n\n" +
            "revisionId: 123456\n" +
            "timestamp: 2026-02-07T10:00:00Z\n"
    );

    JButton btnClose = new JButton("Close");
    btnClose.addActionListener(e -> dlg.dispose());

    dlg.add(new JScrollPane(area), BorderLayout.CENTER);

    JPanel bottom = new JPanel(new FlowLayout(FlowLayout.RIGHT));
    bottom.add(btnClose);
    dlg.add(bottom, BorderLayout.SOUTH);

    dlg.setSize(520, 360);
    dlg.setLocationRelativeTo(this);
    dlg.setVisible(true);

    setStatus("Closed details", false);
}

// ==============================
// Εικόνα 1.2: Save confirm
// ==============================
private void showSaveConfirm() {
    String title = getSelectedTitleOrWarn();
    if (title == null) return;

    int choice = JOptionPane.showConfirmDialog(
            this,
            "Save article?\n\n" + title,
            "Save Confirmation",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
    );

    if (choice == JOptionPane.YES_OPTION) {
        setStatus("Saved: " + title, false);
    } else {
        setStatus("Save cancelled", false);
    }
}

// ==============================
// Εικόνα 1.3: Open in Browser
// ==============================
private void openInBrowser() {
    String title = getSelectedTitleOrWarn();
    if (title == null) return;

    int choice = JOptionPane.showConfirmDialog(
            this,
            "Open in browser?\n\n" + title,
            "Open in Browser",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
    );

    if (choice != JOptionPane.YES_OPTION) {
        setStatus("Open cancelled", false);
        return;
    }

    try {
        String url = "https://en.wikipedia.org/wiki/" + title.trim().replace(" ", "_");
        if (Desktop.isDesktopSupported()) {
            Desktop.getDesktop().browse(new URI(url));
            JOptionPane.showMessageDialog(this, "Opened:\n" + url,
                    "Browser", JOptionPane.INFORMATION_MESSAGE);
            setStatus("Opened in browser", false);
        } else {
            JOptionPane.showMessageDialog(this, "Desktop browse not supported.",
                    "Browser", JOptionPane.WARNING_MESSAGE);
            setStatus("Browser not supported", false);
        }
    } catch (Exception ex) {
        logger.log(java.util.logging.Level.SEVERE, "Open in browser failed", ex);
        JOptionPane.showMessageDialog(this, "Failed to open browser:\n" + ex.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        setStatus("Open failed", false);
    }
}

private void setStatus(String msg, boolean busy) {
    if (lblStatus != null) lblStatus.setText(msg);
    if (progress != null) progress.setVisible(busy);
}

    
    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        // TODO add your handling code here:
         dispose(); // κλείνει το MainFrame (close frame)
    }//GEN-LAST:event_miExitActionPerformed
private void miClearSearchActionPerformed(java.awt.event.ActionEvent evt) {
    if (txtKeywords == null) return; // postInit δεν έχει τρέξει ακόμη
    clearSearchUI();
}

/*Δεν μπορώ να τον διαγράψω είναι binding sto menoy File παραμένει εντός σχολίων
ισχύει ο από eπανω δεν τρέχει αυτός
    private void miClearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClearSearchActionPerformed
        // TODO add your handling code here:
        System.out.println("Clear Search clicked");
    }//GEN-LAST:event_miClearSearchActionPerformed
*/
    /**
     * @param args the command line arguments
     */
    
    //Η main αφαιρείται μετά την εκτέλεση των δοκιμών
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenu menuExit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuSaved;
    private javax.swing.JMenu menuStats;
    private javax.swing.JMenuItem miClearSearch;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miOpenSavedTab;
    private javax.swing.JMenuItem miOpenStatsTab;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JPanel tabSaved;
    private javax.swing.JPanel tabSearch;
    private javax.swing.JPanel tabStats;
    private javax.swing.JTabbedPane tabsMain;
    // End of variables declaration//GEN-END:variables

}
