
package packageGUI;


public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSearchMode = new javax.swing.ButtonGroup();
        pnlTop = new javax.swing.JPanel();
        lblKeywords = new javax.swing.JLabel();
        txtKeywords = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        rbDbOnly = new javax.swing.JRadioButton();
        rbDbApi = new javax.swing.JRadioButton();
        tabsMain = new javax.swing.JTabbedPane();
        tabSearch = new javax.swing.JPanel();
        tabSaved = new javax.swing.JPanel();
        tabStats = new javax.swing.JPanel();
        mainMenuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        miClearSearch = new javax.swing.JMenuItem();
        menuSaved = new javax.swing.JMenu();
        miOpenSavedTab = new javax.swing.JMenuItem();
        menuStats = new javax.swing.JMenu();
        miOpenStatsTab = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenu();
        miExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Καρτέλα Επιλογών WiKi");

        lblKeywords.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblKeywords.setText("Keywords");

        txtKeywords.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnSearch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSearch.setText("Search");

        bgSearchMode.add(rbDbOnly);
        rbDbOnly.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbDbOnly.setText("DB only");
        rbDbOnly.setActionCommand("DB_ONLY");

        bgSearchMode.add(rbDbApi);
        rbDbApi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbDbApi.setText("DB/API");
        rbDbApi.setActionCommand("DB_API");

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKeywords, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKeywords, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnSearch)
                .addGap(129, 129, 129)
                .addComponent(rbDbOnly, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbDbApi)
                .addContainerGap())
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKeywords, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbDbOnly, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbDbApi))
                    .addComponent(lblKeywords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        rbDbApi.getAccessibleContext().setAccessibleName("rbDbApi");
        rbDbApi.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(pnlTop, java.awt.BorderLayout.PAGE_START);

        tabsMain.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout tabSearchLayout = new javax.swing.GroupLayout(tabSearch);
        tabSearch.setLayout(tabSearchLayout);
        tabSearchLayout.setHorizontalGroup(
            tabSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        tabSearchLayout.setVerticalGroup(
            tabSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        tabsMain.addTab("Search Articles", tabSearch);
        tabSearch.getAccessibleContext().setAccessibleName("tabSearch");

        javax.swing.GroupLayout tabSavedLayout = new javax.swing.GroupLayout(tabSaved);
        tabSaved.setLayout(tabSavedLayout);
        tabSavedLayout.setHorizontalGroup(
            tabSavedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        tabSavedLayout.setVerticalGroup(
            tabSavedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        tabsMain.addTab("Saved Articles", tabSaved);
        tabSaved.getAccessibleContext().setAccessibleName("tabSaved");
        tabSaved.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout tabStatsLayout = new javax.swing.GroupLayout(tabStats);
        tabStats.setLayout(tabStatsLayout);
        tabStatsLayout.setHorizontalGroup(
            tabStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        tabStatsLayout.setVerticalGroup(
            tabStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        tabsMain.addTab("Stats & Keywords", tabStats);
        tabStats.getAccessibleContext().setAccessibleName("tabStats");

        getContentPane().add(tabsMain, java.awt.BorderLayout.CENTER);
        tabsMain.getAccessibleContext().setAccessibleName("tabsMain");
        tabsMain.getAccessibleContext().setAccessibleDescription("");

        mainMenuBar.setToolTipText("");
        mainMenuBar.setName("Καρτέλα Επιλογών WiKi"); // NOI18N

        menuFile.setText("File");
        menuFile.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        miClearSearch.setText("Clear Search");
        miClearSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClearSearchActionPerformed(evt);
            }
        });
        menuFile.add(miClearSearch);
        miClearSearch.getAccessibleContext().setAccessibleName("miClearSearch");
        miClearSearch.getAccessibleContext().setAccessibleDescription("");

        mainMenuBar.add(menuFile);
        menuFile.getAccessibleContext().setAccessibleName("menuFile");

        menuSaved.setText("Saved");
        menuSaved.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        miOpenSavedTab.setText("Saved Articles");
        menuSaved.add(miOpenSavedTab);
        miOpenSavedTab.getAccessibleContext().setAccessibleName("miOpenSavedTab");

        mainMenuBar.add(menuSaved);
        menuSaved.getAccessibleContext().setAccessibleName("menuSaved");

        menuStats.setText("Stats");
        menuStats.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        miOpenStatsTab.setText("Statistics");
        menuStats.add(miOpenStatsTab);
        miOpenStatsTab.getAccessibleContext().setAccessibleName("miOpenStatsTab");

        mainMenuBar.add(menuStats);
        menuStats.getAccessibleContext().setAccessibleName("menuStats");

        menuExit.setText("Exit");
        menuExit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        menuExit.add(miExit);
        miExit.getAccessibleContext().setAccessibleName("miExit");
        miExit.getAccessibleContext().setAccessibleDescription("");

        mainMenuBar.add(menuExit);
        menuExit.getAccessibleContext().setAccessibleName("menuExit");

        setJMenuBar(mainMenuBar);
        mainMenuBar.getAccessibleContext().setAccessibleName("mainMenuBar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        // TODO add your handling code here:
         dispose(); // κλείνει το MainFrame (close frame)
    }//GEN-LAST:event_miExitActionPerformed

    private void miClearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClearSearchActionPerformed
        // TODO add your handling code here:
        System.out.println("Clear Search clicked");
    }//GEN-LAST:event_miClearSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSearchMode;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel lblKeywords;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenu menuExit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuSaved;
    private javax.swing.JMenu menuStats;
    private javax.swing.JMenuItem miClearSearch;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miOpenSavedTab;
    private javax.swing.JMenuItem miOpenStatsTab;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JRadioButton rbDbApi;
    private javax.swing.JRadioButton rbDbOnly;
    private javax.swing.JPanel tabSaved;
    private javax.swing.JPanel tabSearch;
    private javax.swing.JPanel tabStats;
    private javax.swing.JTabbedPane tabsMain;
    private javax.swing.JTextField txtKeywords;
    // End of variables declaration//GEN-END:variables
}
