
package packageGUI;

import packageController.*;
import packageAPI.export.DocxExporter;
import packageAPI.export.PdfExporter;


import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.RenderingHints;
import java.awt.Toolkit;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import java.net.URI;
import java.nio.file.Path;
import java.io.File;


import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
/**
 * Καλούνται Νήματα (Treads)
 * Threads καλούνται στο: packageGUI 
 * Συγκεκριμένα: MainFrame.java
 * Μηχανισμός: SwingWorker
 * 
 * Σκοπός να μήν "Παγώνει" το GUI όταν καθυστερούν οι απαντήσεις
 * Για να δείς σε ποιά καλείται κάνε Ctrl + F kai βάλε SwingWorker
 * 
 * Γίνεται στα 
 * Search Articles → όταν καλεί controller.search(...)
 * Saved Articles → όταν φορτώνει αποθηκευμένα
 * Stats → όταν καλεί controller.loadStats()
 * 
 * /

/**
 * MainFrame – UI shell (Builder) + UI content (postInit).
 */
/** 
 * Εδώ ορίζω το class <b>MainFrame</b> στο GUI [γραφικό περιβάλλον χρήστη].
 * <p>Στόχος μου είναι να κρατήσω το κομμάτι αυτό καθαρό και καλά σχολιασμένο, ώστε να μπορεί να συνεχίσει εύκολα άλλο μέλος της ομάδας.</p>
 */
public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(MainFrame.class.getName());

    // ===============================
    // Controller (GUI -> Controller)
    // ===============================
    private final WikiController controller;

    // Cache για να βρίσκω metadata (rating/comments) όταν επιλέγω γραμμή στο Saved table.
    private final Map<Long, SavedArticleRow> savedCacheById = new LinkedHashMap<>();

    /**

     * Εδώ αρχικοποιώ το <b>MainFrame</b>.

     * Φροντίζω να στήσω την αρχική κατάσταση του αντικειμένου (fields, defaults, listeners κ.λπ.).

     */

    /**

     * Εδώ υλοποιώ τη μέθοδο <b>MainFrame()</b>.

     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

     * @return Επιστρέφω αποτέλεσμα.

     */

    public MainFrame() {
        this(new WikiControllerImpl());
    }

    /**

     * Εδώ αρχικοποιώ το <b>MainFrame</b>.

     * Φροντίζω να στήσω την αρχική κατάσταση του αντικειμένου (fields, defaults, listeners κ.λπ.).

     * @param controller Παράμετρος αρχικοποίησης.

     */

    /**

     * Εδώ υλοποιώ τη μέθοδο <b>MainFrame()</b>.

     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

     * @param controller Παράμετρος εισόδου.

     * @return Επιστρέφω αποτέλεσμα.

     */

    public MainFrame(WikiController controller) {
        this.controller = (controller == null) ? new WikiControllerImpl() : controller;
        initComponents();   // εδώ αφήνω μόνο τον “σκελετό” που φτιάχνει ο Builder
        postInit();         // εδώ χτίζω Εικόνα 1–2–3 + listeners, ώστε να μην με δένει το initComponents()
    }
    
    /**
     * μετά την εκτέλεση - ολοκλήρωση των δοκιμών αφαιρούμε την main
     * public static void main(String args[])  
     * Η εφαρμογή Εκκινείται από την 
     * App.java του package packageMain
     * Εχει ΗΔΗ ΑΦΑΙΡΕΘΕΙ
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * δεσμευτικός από την σχεδίαση του Swing
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    /**
     * Εδώ υλοποιώ τη μέθοδο <b>initComponents()</b>.
     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
     */
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        tabsMain = new javax.swing.JTabbedPane();
        tabSearch = new javax.swing.JPanel();
        tabSaved = new javax.swing.JPanel();
        tabStats = new javax.swing.JPanel();
        mainMenuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        miClearSearch = new javax.swing.JMenuItem();
        menuSaved = new javax.swing.JMenu();
        miOpenSavedTab = new javax.swing.JMenuItem();
        menuStats = new javax.swing.JMenu();
        miOpenStatsTab = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenu();
        miExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Καρτέλα Επιλογών WiKi");

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1171, Short.MAX_VALUE)
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        getContentPane().add(pnlTop, java.awt.BorderLayout.PAGE_START);

        tabsMain.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout tabSearchLayout = new javax.swing.GroupLayout(tabSearch);
        tabSearch.setLayout(tabSearchLayout);
        tabSearchLayout.setHorizontalGroup(
            tabSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1171, Short.MAX_VALUE)
        );
        tabSearchLayout.setVerticalGroup(
            tabSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        tabsMain.addTab("Search Articles", tabSearch);
        tabSearch.getAccessibleContext().setAccessibleName("tabSearch");

        javax.swing.GroupLayout tabSavedLayout = new javax.swing.GroupLayout(tabSaved);
        tabSaved.setLayout(tabSavedLayout);
        tabSavedLayout.setHorizontalGroup(
            tabSavedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1171, Short.MAX_VALUE)
        );
        tabSavedLayout.setVerticalGroup(
            tabSavedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        tabsMain.addTab("Saved Articles", tabSaved);
        tabSaved.getAccessibleContext().setAccessibleName("tabSaved");
        tabSaved.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout tabStatsLayout = new javax.swing.GroupLayout(tabStats);
        tabStats.setLayout(tabStatsLayout);
        tabStatsLayout.setHorizontalGroup(
            tabStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1171, Short.MAX_VALUE)
        );
        tabStatsLayout.setVerticalGroup(
            tabStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        tabsMain.addTab("Stats & Keywords", tabStats);
        tabStats.getAccessibleContext().setAccessibleName("tabStats");

        getContentPane().add(tabsMain, java.awt.BorderLayout.CENTER);
        tabsMain.getAccessibleContext().setAccessibleName("tabsMain");
        tabsMain.getAccessibleContext().setAccessibleDescription("");

        mainMenuBar.setToolTipText("");
        mainMenuBar.setName("Καρτέλα Επιλογών WiKi"); // NOI18N

        menuFile.setText("File");
        menuFile.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        miClearSearch.setText("Clear Search");
        miClearSearch.addActionListener(new java.awt.event.ActionListener() {
            /**
             * Εδώ υλοποιώ τη μέθοδο <b>actionPerformed()</b>.
             * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
             * @param evt Παράμετρος εισόδου.
             */
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClearSearchActionPerformed(evt);
            }
        });
        menuFile.add(miClearSearch);
        miClearSearch.getAccessibleContext().setAccessibleName("miClearSearch");
        miClearSearch.getAccessibleContext().setAccessibleDescription("");

        mainMenuBar.add(menuFile);
        menuFile.getAccessibleContext().setAccessibleName("menuFile");

        menuSaved.setText("Saved");
        menuSaved.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        miOpenSavedTab.setText("Saved Articles");
        menuSaved.add(miOpenSavedTab);
        miOpenSavedTab.getAccessibleContext().setAccessibleName("miOpenSavedTab");

        mainMenuBar.add(menuSaved);
        menuSaved.getAccessibleContext().setAccessibleName("menuSaved");

        menuStats.setText("Stats");
        menuStats.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        miOpenStatsTab.setText("Statistics");
        menuStats.add(miOpenStatsTab);
        miOpenStatsTab.getAccessibleContext().setAccessibleName("miOpenStatsTab");

        mainMenuBar.add(menuStats);
        menuStats.getAccessibleContext().setAccessibleName("menuStats");

        menuExit.setText("Exit");
        menuExit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            /**
             * Εδώ υλοποιώ τη μέθοδο <b>actionPerformed()</b>.
             * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
             * @param evt Παράμετρος εισόδου.
             */
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        menuExit.add(miExit);
        miExit.getAccessibleContext().setAccessibleName("miExit");
        miExit.getAccessibleContext().setAccessibleDescription("");

        mainMenuBar.add(menuExit);
        menuExit.getAccessibleContext().setAccessibleName("menuExit");

        setJMenuBar(mainMenuBar);
        mainMenuBar.getAccessibleContext().setAccessibleName("mainMenuBar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

 // =========================================================
    // 1) UI fields (χτίζω τα components μόνος μου στο postInit)
    // =========================================================

    // ---- Top controls (Εικόνα 1)
    private JTextField txtKeywords;
    private JButton btnSearch;
    private JButton btnClear;
    private JRadioButton rbDbOnly;
    private JRadioButton rbDbApi;
    private ButtonGroup bgSearchMode;

    // ---- Shared category model (κοινό για Search + Saved)
    private final DefaultComboBoxModel<String> categoriesComboModel = new DefaultComboBoxModel<>();
    private final Map<String, Boolean> categoryChecked = new LinkedHashMap<>(); // κρατάω checked state για τις checkbox λίστες

    // ---- Search tab (Εικόνα 1) (placeholder απλό)
    private CategoryCheckList listCategoriesSearch;
    private JTable tblResults;
    private DefaultTableModel resultsModel;
    private JTextArea txtPreview;
    private JButton btnViewDetails;
    private JButton btnSave;
    private JButton btnOpenInBrowser;

    // ---- Search tab extra fields (Rating + Comments)
    private JSlider sldSearchRating;          // 0..5
    private JLabel lblSearchStars;            // ***** (colored)
    private JTextArea txtSearchComments;      // with scroll


    // ---- Saved tab (Εικόνα 2) (placeholder απλό)
    private CategoryCheckList listCategoriesSaved;
    private JTable tblSaved;
    private DefaultTableModel savedModel;
    private JTextArea txtSavedPreview;
    private JButton btnLoadArticle;
    private JButton btnDelete;
    private JButton btnClearList;
    private JLabel lblSavedCount;

    // ---- Saved tab extra fields (Rating + Comments)
    private JSlider sldSavedRating;           // 0..5
    private JLabel lblSavedStars;             // ***** (colored)
    private JTextArea txtSavedComments;       // with scroll


    // ---- Stats tab (Εικόνα 3)
    private JTable tblKeywordStats;                 // πίνακας keyword/count
    private DefaultTableModel keywordStatsModel;

    private JTable tblCategoryLegend;               // legend (category -> articles)
    private DefaultTableModel categoryLegendModel;

    private JLabel lblStatsSelected;                // "Selected: ..."
    private JLabel lblStatsSavedCount;              // "4 saved articles ▼"

    private HorizontalBarsPanel pnlKeywordBarsSmall;
    private HorizontalBarsPanel pnlKeywordBarsBig;

    private PieChartPanel pnlCategoryPie;
    private VerticalBarsPanel pnlCategoryBars;

    // ---- Status bar (κάτω στο frame)
    private JLabel lblStatus;
    private JProgressBar progress;

 
    // =========================================================
    // 2) postInit = ΟΛΟ το UI των Εικόνων 1–2–3 + listeners
    // =========================================================
    /**
     * Εδώ υλοποιώ τη μέθοδο <b>postInit()</b>.
     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
     */
    private void postInit() {
        // Φτιάχνω κοινές κατηγορίες (από εδώ θα “ταΐζονται” sidebar + dialogs).
        initCategories();

        // Χτίζω Top (Εικόνα 1).
        buildTopWrapper();

        // Χτίζω tabs:
        buildSearchTabUI(); // Εικόνα 1 (placeholder)
        buildSavedTabUI();  // Εικόνα 2 (placeholder)
        buildStatsTabUI();  // Εικόνα 3 (το ζητούμενο)

        // Χτίζω status bar κάτω.
        buildStatusBar();

        // Δένω menu navigation στα tabs.
        wireMenuNavigation();
        tabsMain.addChangeListener(e -> {
            if (tabsMain.getSelectedComponent() == tabSaved) {
                reloadSavedArticles();
            }
        });


        // Default επιλογές.
        setStatus("Ready", false);
        tabsMain.setSelectedComponent(tabSearch);

        // Αρχικό φόρτωμα δεδομένων από Controller (dummy προς το παρόν).
        refreshSavedInBackground();
        refreshStatsInBackground();

        // Ρυθμίζω μέγεθος παραθύρου.
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int w = (int) (screen.width * 0.85);
        int h = (int) (screen.height * 0.78);
        setSize(w, h);
        setLocationRelativeTo(null);
        setMinimumSize(new Dimension(1000, 650));
    }

    // =========================================================
    // 3) Categories – κοινή πηγή αλήθειας για UI
    // =========================================================
    /**
     * Εδώ υλοποιώ τη μέθοδο <b>initCategories()</b>.
     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
     */
    private void initCategories() {
        categoriesComboModel.removeAllElements();
        categoryChecked.clear();

        addCategoryInternal("Όλες οι κατηγορίες");
        addCategoryInternal("Χωρίς Κατηγορία");
        addCategoryInternal("Πολιτισμός");
        addCategoryInternal("Ιστορία");
        addCategoryInternal("Υπολογιστές");
    }

    /**

     * Εδώ υλοποιώ τη μέθοδο <b>addCategoryInternal()</b>.

     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

     * @param name Παράμετρος εισόδου.

     */

    private void addCategoryInternal(String name) {
        categoriesComboModel.addElement(name);
        categoryChecked.put(name, "Όλες οι κατηγορίες".equals(name));
    }

    /**

     * Εδώ υλοποιώ τη μέθοδο <b>addNewCategoryFromUser()</b>.

     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

     * @param name Παράμετρος εισόδου.

     */

    private void addNewCategoryFromUser(String name) {
        String n = (name == null) ? "" : name.trim();
        if (n.isEmpty()) return;

        for (int i = 0; i < categoriesComboModel.getSize(); i++) {
            if (n.equalsIgnoreCase(categoriesComboModel.getElementAt(i))) {
                setStatus("Η κατηγορία υπάρχει ήδη: " + n, false);
                return;
            }
        }

        categoriesComboModel.addElement(n);
        categoryChecked.put(n, false);

        if (listCategoriesSearch != null) listCategoriesSearch.refreshFromModel();
        if (listCategoriesSaved != null) listCategoriesSaved.refreshFromModel();

        setStatus("Πρόσθεσα νέα κατηγορία: " + n, false);
    }

    /**

     * Εδώ υλοποιώ τη μέθοδο <b>getCheckedCategories()</b>.

     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

     * @return Επιστρέφω αποτέλεσμα.

     */

    private List<String> getCheckedCategories() {
        List<String> out = new ArrayList<>();
        for (Map.Entry<String, Boolean> e : categoryChecked.entrySet()) {
            if (Boolean.TRUE.equals(e.getValue())) out.add(e.getKey());
        }
        return out;
    }

/**
 * Formats categories list for table cell.
 * Example: ["Υπολογιστές","ΑΙ","Προγραμματισμός"] -> "Υπολογιστές, ΑΙ, Προγραμματισμός"
 */
/**
 * Εδώ υλοποιώ τη μέθοδο <b>formatCategories()</b>.
 * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
 * @param categories Παράμετρος εισόδου.
 * @return Επιστρέφω αποτέλεσμα.
 */
private String formatCategories(java.util.List<String> categories) {
    if (categories == null || categories.isEmpty()) return "Χωρίς Κατηγορία";
    return String.join(", ", categories);
}


    // =========================================================
    // 4) Top wrapper (Εικόνα 1)
    // =========================================================
    /**
     * Εδώ υλοποιώ τη μέθοδο <b>buildTopWrapper()</b>.
     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
     */
    private void buildTopWrapper() {
        JPanel topControls = new JPanel(new FlowLayout(FlowLayout.LEFT, 8, 8));

        JLabel lbl = new JLabel("Keywords");
        lbl.setFont(new Font("Arial", Font.PLAIN, 14));

        txtKeywords = new JTextField(30);
        txtKeywords.setFont(new Font("Arial", Font.PLAIN, 14));

        btnSearch = new JButton("Search");
        btnSearch.setFont(new Font("Arial", Font.PLAIN, 14));

        btnClear = new JButton("Clear");
        btnClear.setFont(new Font("Arial", Font.PLAIN, 14));

        rbDbOnly = new JRadioButton("DB only");
        rbDbOnly.setFont(new Font("Arial", Font.PLAIN, 14));
        rbDbOnly.setActionCommand("DB_ONLY");

        rbDbApi = new JRadioButton("DB/API");
        rbDbApi.setFont(new Font("Arial", Font.PLAIN, 14));
        rbDbApi.setActionCommand("DB_API");

        bgSearchMode = new ButtonGroup();
        bgSearchMode.add(rbDbOnly);
        bgSearchMode.add(rbDbApi);
        rbDbApi.setSelected(true);

        topControls.add(lbl);
        topControls.add(txtKeywords);
        topControls.add(btnSearch);
        topControls.add(btnClear);
        topControls.add(rbDbOnly);
        topControls.add(rbDbApi);

        // Κάνω wrapper ώστε να μην πειράζω το GroupLayout του pnlTop (generated).
        JPanel pnlTopWrapper = new JPanel(new BorderLayout());
        pnlTopWrapper.add(topControls, BorderLayout.WEST);

        Container content = getContentPane();
        content.remove(pnlTop);
        pnlTopWrapper.add(pnlTop, BorderLayout.CENTER);
        content.add(pnlTopWrapper, BorderLayout.PAGE_START);

        // Listeners [ακροατές]
        btnSearch.addActionListener(e -> onSearch());
        txtKeywords.addActionListener(e -> onSearch());
        btnClear.addActionListener(e -> clearSearchUI());

        content.revalidate();
        content.repaint();
    }

    // =========================================================
    // 5) Search tab – (placeholder απλό για να “δένει” το project)
    // =========================================================
    /**
     * Εδώ υλοποιώ τη μέθοδο <b>buildSearchTabUI()</b>.
     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
     */
    private void buildSearchTabUI() {
        tabSearch.removeAll();
        tabSearch.setLayout(new BorderLayout(10, 10));

        listCategoriesSearch = new CategoryCheckList("Κατηγορίες (Search)");
        JScrollPane spCats = new JScrollPane(listCategoriesSearch);
        spCats.setPreferredSize(new Dimension(220, 10));

        JButton btnNewCategory = new JButton("Νέα Κατηγορία");
        btnNewCategory.addActionListener(e -> promptNewCategory());

        JPanel pnlCats = new JPanel(new BorderLayout(6, 6));
        pnlCats.add(spCats, BorderLayout.CENTER);
        pnlCats.add(btnNewCategory, BorderLayout.SOUTH);

        resultsModel = new DefaultTableModel(
                new Object[0][0],
                new String[]{"Title", "Source", "Category", "PageId"}
        ) {
            /**
             * Εδώ υλοποιώ τη μέθοδο <b>isCellEditable()</b>.
             * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
             * @param r Παράμετρος εισόδου.
             * @param c Παράμετρος εισόδου.
             * @return Επιστρέφω αποτέλεσμα.
             */
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };

        tblResults = new JTable(resultsModel);
        tblResults.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblResults.setAutoCreateRowSorter(true);

        // κρύβω PageId
        tblResults.getColumnModel().getColumn(3).setMinWidth(0);
        tblResults.getColumnModel().getColumn(3).setMaxWidth(0);
        tblResults.getColumnModel().getColumn(3).setPreferredWidth(0);

        JScrollPane spResults = new JScrollPane(tblResults);

        txtPreview = new JTextArea();
        txtPreview.setEditable(false);
        txtPreview.setLineWrap(true);
        txtPreview.setWrapStyleWord(true);
        txtPreview.setFont(new Font("Arial", Font.PLAIN, 13));
        txtPreview.setMargin(new Insets(10, 10, 10, 10));
        txtPreview.setText("Preview κειμένου (placeholder)…");
        JScrollPane spPreview = new JScrollPane(txtPreview);

        JSplitPane splitTablePreview = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, spResults, spPreview);
        splitTablePreview.setResizeWeight(0.62);

        JSplitPane splitMain = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, pnlCats, splitTablePreview);
        splitMain.setResizeWeight(0.18);

        JPanel pnlButtons = new JPanel(new FlowLayout(FlowLayout.LEFT, 10, 8));
        btnViewDetails = new JButton("View Details");
        btnSave = new JButton("Save");
        btnOpenInBrowser = new JButton("Open in Browser");
        pnlButtons.add(btnViewDetails);
        pnlButtons.add(btnSave);
        pnlButtons.add(btnOpenInBrowser);

        // --- NEW: Rating (0..5) + Comments (with scroll) [Search tab]
        JLabel lblRating = new JLabel("Βαθμολογία");
        lblRating.setFont(new Font("Arial", Font.PLAIN, 13));

        sldSearchRating = new JSlider(0, 5, 0);
        sldSearchRating.setMajorTickSpacing(1);
        sldSearchRating.setPaintTicks(true);
        sldSearchRating.setPaintLabels(true);

        lblSearchStars = new JLabel(starsHtml(0));
        lblSearchStars.setFont(new Font("Arial", Font.BOLD, 16));

        JPanel pnlRating = new JPanel(new FlowLayout(FlowLayout.LEFT, 8, 0));
        pnlRating.add(lblRating);
        pnlRating.add(lblSearchStars);
        pnlRating.add(sldSearchRating);

        JLabel lblComments = new JLabel("Σχόλια");
        lblComments.setFont(new Font("Arial", Font.PLAIN, 13));

        txtSearchComments = new JTextArea(3, 28);
        txtSearchComments.setLineWrap(true);
        txtSearchComments.setWrapStyleWord(true);
        JScrollPane spComments = new JScrollPane(txtSearchComments);
        spComments.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
        spComments.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        JPanel pnlComments = new JPanel(new BorderLayout(6, 4));
        pnlComments.add(lblComments, BorderLayout.NORTH);
        pnlComments.add(spComments, BorderLayout.CENTER);

        JPanel pnlRatingComments = new JPanel(new BorderLayout(10, 6));
        pnlRatingComments.add(pnlRating, BorderLayout.WEST);
        pnlRatingComments.add(pnlComments, BorderLayout.CENTER);

        JPanel pnlBottom = new JPanel(new BorderLayout(10, 8));
        pnlBottom.add(pnlButtons, BorderLayout.WEST);
        pnlBottom.add(pnlRatingComments, BorderLayout.CENTER);

        tabSearch.add(splitMain, BorderLayout.CENTER);
        tabSearch.add(pnlBottom, BorderLayout.SOUTH);

        // listener: slider -> stars
        sldSearchRating.addChangeListener(e -> {
            int r = sldSearchRating.getValue();
            lblSearchStars.setText(starsHtml(r));
        });

        tblResults.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if (!e.getValueIsAdjusting()) updateSearchPreviewFromSelection();
        });

        btnOpenInBrowser.addActionListener(e -> openInBrowserFromSearch());
        btnSave.addActionListener(e -> showSaveDialogForSelected());
        btnViewDetails.addActionListener(e -> showDetailsDialogFromSearch());

        listCategoriesSearch.setOnSelectionChanged(() -> { setStatus("Φίλτρο κατηγοριών (Search): " + getCheckedCategories(), false); reloadSearchWithCurrentQuery(); });

        tabSearch.revalidate();
        tabSearch.repaint();
    }

    /**

     * Εδώ υλοποιώ τη μέθοδο <b>updateSearchPreviewFromSelection()</b>.

     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

     */

    private void updateSearchPreviewFromSelection() {
        int rowView = tblResults.getSelectedRow();
        if (rowView < 0) return;

        int row = tblResults.convertRowIndexToModel(rowView);
        String title = String.valueOf(resultsModel.getValueAt(row, 0));
        String source = String.valueOf(resultsModel.getValueAt(row, 1));
        String category = String.valueOf(resultsModel.getValueAt(row, 2));

        txtPreview.setText(
                "Title: " + title + "\n" +
                "Source: " + source + "\n" +
                "Category: " + category + "\n\n" +
                "Preview κειμένου (placeholder)…"
        );

        setStatus("Selected: " + title, false);
    }

    // =========================================================
    // 6) Saved tab – (placeholder απλό για να “δένει” το project)
    // =========================================================
    /**
     * Εδώ υλοποιώ τη μέθοδο <b>buildSavedTabUI()</b>.
     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
     */
    private void buildSavedTabUI() {
        tabSaved.removeAll();
        tabSaved.setLayout(new BorderLayout(10, 10));

        listCategoriesSaved = new CategoryCheckList("Κατηγορίες (Saved)");
        JScrollPane spCats = new JScrollPane(listCategoriesSaved);
        spCats.setPreferredSize(new Dimension(220, 10));

        JButton btnNewCategory = new JButton("Νέα Κατηγορία");
        btnNewCategory.addActionListener(e -> promptNewCategory());

        JPanel pnlCats = new JPanel(new BorderLayout(6, 6));
        pnlCats.add(spCats, BorderLayout.CENTER);
        pnlCats.add(btnNewCategory, BorderLayout.SOUTH);

        savedModel = new DefaultTableModel(
                new Object[0][0],
                new String[]{"Title", "PageId", "Saved At", "Source", "Category"}
        ) {
            /**
             * Εδώ υλοποιώ τη μέθοδο <b>isCellEditable()</b>.
             * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
             * @param r Παράμετρος εισόδου.
             * @param c Παράμετρος εισόδου.
             * @return Επιστρέφω αποτέλεσμα.
             */
            @Override public boolean isCellEditable(int r, int c) { return false; }
            /**
             * Εδώ υλοποιώ τη μέθοδο <b>getColumnClass()</b>.
             * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
             * @param col Παράμετρος εισόδου.
             * @return Επιστρέφω αποτέλεσμα.
             */
            @Override public Class<?> getColumnClass(int col) {
                return (col == 1) ? Long.class : String.class;
            }
        };

        tblSaved = new JTable(savedModel);
        tblSaved.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblSaved.setAutoCreateRowSorter(true);
        JScrollPane spSaved = new JScrollPane(tblSaved);

        txtSavedPreview = new JTextArea();
        txtSavedPreview.setEditable(false);
        txtSavedPreview.setLineWrap(true);
        txtSavedPreview.setWrapStyleWord(true);
        txtSavedPreview.setFont(new Font("Arial", Font.PLAIN, 13));
        txtSavedPreview.setMargin(new Insets(10, 10, 10, 10));
        txtSavedPreview.setText("Title:\n\nPreview κειμένου (placeholder)…");
        JScrollPane spSavedPreview = new JScrollPane(txtSavedPreview);

        JSplitPane splitTablePreview = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, spSaved, spSavedPreview);
        splitTablePreview.setResizeWeight(0.62);

        JSplitPane splitMain = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, pnlCats, splitTablePreview);
        splitMain.setResizeWeight(0.18);

        JPanel pnlBottom = new JPanel(new BorderLayout(10, 8));

        JPanel pnlButtons = new JPanel(new FlowLayout(FlowLayout.LEFT, 10, 8));
        btnLoadArticle = new JButton("Load Article");
        btnDelete = new JButton("Delete");
        btnClearList = new JButton("Clear List");
        pnlButtons.add(btnLoadArticle);
        pnlButtons.add(btnDelete);
        pnlButtons.add(btnClearList);

        // --- NEW: Rating (0..5) + Comments (with scroll) [Saved tab]
        JLabel lblRating = new JLabel("Βαθμολογία");
        lblRating.setFont(new Font("Arial", Font.PLAIN, 13));

        sldSavedRating = new JSlider(0, 5, 0);
        sldSavedRating.setMajorTickSpacing(1);
        sldSavedRating.setPaintTicks(true);
        sldSavedRating.setPaintLabels(true);

        lblSavedStars = new JLabel(starsHtml(0));
        lblSavedStars.setFont(new Font("Arial", Font.BOLD, 16));

        JPanel pnlRating = new JPanel(new FlowLayout(FlowLayout.LEFT, 8, 0));
        pnlRating.add(lblRating);
        pnlRating.add(lblSavedStars);
        pnlRating.add(sldSavedRating);

        JLabel lblComments = new JLabel("Σχόλια");
        lblComments.setFont(new Font("Arial", Font.PLAIN, 13));

        txtSavedComments = new JTextArea(3, 28);
        txtSavedComments.setLineWrap(true);
        txtSavedComments.setWrapStyleWord(true);
        JScrollPane spComments = new JScrollPane(txtSavedComments);
        spComments.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
        spComments.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        JPanel pnlComments = new JPanel(new BorderLayout(6, 4));
        pnlComments.add(lblComments, BorderLayout.NORTH);
        pnlComments.add(spComments, BorderLayout.CENTER);

        JPanel pnlRatingComments = new JPanel(new BorderLayout(10, 6));
        pnlRatingComments.add(pnlRating, BorderLayout.WEST);
        pnlRatingComments.add(pnlComments, BorderLayout.CENTER);

        lblSavedCount = new JLabel();
        lblSavedCount.setFont(new Font("Arial", Font.PLAIN, 12));
        updateSavedCount();

        JPanel pnlCount = new JPanel(new FlowLayout(FlowLayout.RIGHT, 10, 8));
        pnlCount.add(lblSavedCount);

        pnlBottom.add(pnlButtons, BorderLayout.WEST);
        pnlBottom.add(pnlRatingComments, BorderLayout.CENTER);
        pnlBottom.add(pnlCount, BorderLayout.EAST);

        // listener: slider -> stars
        sldSavedRating.addChangeListener(e -> {
            int r = sldSavedRating.getValue();
            lblSavedStars.setText(starsHtml(r));
        });

        tabSaved.add(splitMain, BorderLayout.CENTER);
        tabSaved.add(pnlBottom, BorderLayout.SOUTH);

        tblSaved.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) updateSavedPreviewFromSelection();
        });

        btnDelete.addActionListener(e -> deleteSelectedSaved());
        btnClearList.addActionListener(e -> clearAllSaved());
        btnLoadArticle.addActionListener(e -> showLoadDialogFromSaved());

        listCategoriesSaved.setOnSelectionChanged(() -> { setStatus("Φίλτρο κατηγοριών (Saved): " + getCheckedCategories(), false); reloadSavedArticles(); });

        tabSaved.revalidate();
        tabSaved.repaint();
    }

    /**

     * Εδώ υλοποιώ τη μέθοδο <b>updateSavedPreviewFromSelection()</b>.

     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

     */

    private void updateSavedPreviewFromSelection() {
    int rowView = tblSaved.getSelectedRow();
    if (rowView < 0) return;

    int row = tblSaved.convertRowIndexToModel(rowView);
    String title = String.valueOf(savedModel.getValueAt(row, 0));
    Object pageIdObj = savedModel.getValueAt(row, 1);
    long pageId = (pageIdObj instanceof Number) ? ((Number) pageIdObj).longValue() : Long.parseLong(String.valueOf(pageIdObj));
    String savedAt = String.valueOf(savedModel.getValueAt(row, 2));
    String source = String.valueOf(savedModel.getValueAt(row, 3));
    String category = String.valueOf(savedModel.getValueAt(row, 4));

    txtSavedPreview.setText(
            "Title: " + title + "\n" +
            "PageId: " + pageId + "\n" +
            "Saved At: " + savedAt + "\n" +
            "Source: " + source + "\n" +
            "Category: " + category + "\n"
    );

    // Load metadata (rating/comments) from controller (dummy for now).
    loadSavedMetadata(pageId);

    setStatus("Saved selected: " + title, false);
}


    /**


     * Εδώ υλοποιώ τη μέθοδο <b>updateSavedCount()</b>.


     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.


     */


    private void updateSavedCount() {
        int n = (savedModel == null) ? 0 : savedModel.getRowCount();
        lblSavedCount.setText(n + " saved articles ✓");
    }

    // =========================================================
    // 6.1) Data binding: Controller -> UI models
    // =========================================================
    /**
     * Εδώ υλοποιώ τη μέθοδο <b>setSearchResults()</b>.
     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
     * @param rows Παράμετρος εισόδου.
     */
    private void setSearchResults(List<SearchResultRow> rows) {
        if (resultsModel == null) return;
        resultsModel.setRowCount(0);
        if (rows == null) return;

        for (SearchResultRow r : rows) {
            resultsModel.addRow(new Object[]{r.title(), r.source(), formatCategories(r.categories()), r.pageId()});
        }

        if (tblResults != null) tblResults.clearSelection();
        if (txtPreview != null) txtPreview.setText("Preview κειμένου (placeholder)…");
    }

    /**

     * Εδώ υλοποιώ τη μέθοδο <b>setSavedRows()</b>.

     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

     * @param rows Παράμετρος εισόδου.

     */

    private void setSavedRows(List<SavedArticleRow> rows) {
        if (savedModel == null) return;

        savedCacheById.clear();
        savedModel.setRowCount(0);

        if (rows != null) {
            for (SavedArticleRow r : rows) {
                savedCacheById.put(r.pageId(), r);
                savedModel.addRow(new Object[]{r.title(), r.pageId(), r.savedAt(), r.source(), formatCategories(r.categories())});
            }
        }

        updateSavedCount();
        if (lblStatsSavedCount != null) {
            int n = savedModel.getRowCount();
            lblStatsSavedCount.setText(n + " saved articles ▼");
        }
    }

    /**

     * Εδώ υλοποιώ τη μέθοδο <b>refreshSavedInBackground()</b>.

     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

     */

    private void refreshSavedInBackground() {
        setStatus("Loading saved articles…", true);
        new SwingWorker<List<SavedArticleRow>, Void>() {
            /**
             * Εδώ υλοποιώ τη μέθοδο <b>doInBackground()</b>.
             * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
             * @return Επιστρέφω αποτέλεσμα.
             */
            @Override
            protected List<SavedArticleRow> doInBackground() {
                return controller.listSaved(getCheckedCategories());
            }

            /**

             * Εδώ υλοποιώ τη μέθοδο <b>done()</b>.

             * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

             */

            @Override
            protected void done() {
                try {
                    setSavedRows(get());
                    setStatus("Ready", false);
                } catch (Exception ex) {
                    logger.log(java.util.logging.Level.SEVERE, "Failed to load saved articles", ex);
                    setStatus("Load saved failed", false);
                }
            }
        }.execute();
    }

    /**

     * Εδώ υλοποιώ τη μέθοδο <b>refreshStatsInBackground()</b>.

     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

     */

    private void refreshStatsInBackground() {
        setStatus("Loading stats…", true);
        new SwingWorker<StatsSnapshot, Void>() {
            /**
             * Εδώ υλοποιώ τη μέθοδο <b>doInBackground()</b>.
             * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
             * @return Επιστρέφω αποτέλεσμα.
             */
            @Override
            protected StatsSnapshot doInBackground() {
                return controller.loadStats();
            }

            /**

             * Εδώ υλοποιώ τη μέθοδο <b>done()</b>.

             * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

             */

            @Override
            protected void done() {
                try {
                    // απλούστερο: ξαναχτίζω το Stats tab με τα νέα δεδομένα
                    StatsSnapshot snap = get();
                    buildStatsTabUIWithSnapshot(snap);
                    setStatus("Ready", false);
                } catch (Exception ex) {
                    logger.log(java.util.logging.Level.SEVERE, "Failed to load stats", ex);
                    setStatus("Load stats failed", false);
                }
            }
        }.execute();
    }

    // =========================================================
    // 7) Stats tab – Εικόνα 3 (όπως την εικόνα που ανέβασες)
    // =========================================================
    /**
     * Εδώ υλοποιώ τη μέθοδο <b>buildStatsTabUI()</b>.
     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
     */
    private void buildStatsTabUI() {
        buildStatsTabUIWithSnapshot(controller.loadStats());
    }

    /**

     * Εδώ υλοποιώ τη μέθοδο <b>buildStatsTabUIWithSnapshot()</b>.

     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

     * @param snap Παράμετρος εισόδου.

     */

    private void buildStatsTabUIWithSnapshot(StatsSnapshot snap) {
        tabStats.removeAll();
        tabStats.setLayout(new BorderLayout(12, 12));

        // Data από Controller (ακόμη dummy, αλλά ΔΕΝ είναι hardcoded στο GUI)

        LinkedHashMap<String, Integer> keywordCounts = new LinkedHashMap<>();
        for (KeywordStatRow r : snap.keywordStats()) {
            keywordCounts.put(r.keyword(), r.count());
        }

        LinkedHashMap<String, Integer> categoryCounts = new LinkedHashMap<>();
        for (CategoryStatRow r : snap.categoryStats()) {
            // Κάθε γραμμή στο CategoryStatRow αντιστοιχεί σε ΜΙΑ κατηγορία.
            categoryCounts.put(r.category(), r.articles());
        }

        // =========================
        // LEFT panel: Keywords stats
        // =========================
        JPanel pnlLeft = new JPanel(new BorderLayout(10, 10));

        JLabel lblLeftTitle = new JLabel("Συχνότερες αναζητήσεις (Keywords)");
        lblLeftTitle.setFont(new Font("Arial", Font.PLAIN, 16));
        pnlLeft.add(lblLeftTitle, BorderLayout.NORTH);

        keywordStatsModel = new DefaultTableModel(new Object[]{"Keyword", "Count"}, 0) {
            /**
             * Εδώ υλοποιώ τη μέθοδο <b>isCellEditable()</b>.
             * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
             * @param r Παράμετρος εισόδου.
             * @param c Παράμετρος εισόδου.
             * @return Επιστρέφω αποτέλεσμα.
             */
            @Override public boolean isCellEditable(int r, int c) { return false; }
            /**
             * Εδώ υλοποιώ τη μέθοδο <b>getColumnClass()</b>.
             * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
             * @param columnIndex Παράμετρος εισόδου.
             * @return Επιστρέφω αποτέλεσμα.
             */
            @Override public Class<?> getColumnClass(int columnIndex) {
                return (columnIndex == 1) ? Integer.class : String.class;
            }
        };

        for (Map.Entry<String, Integer> e : keywordCounts.entrySet()) {
            keywordStatsModel.addRow(new Object[]{e.getKey(), e.getValue()});
        }

        tblKeywordStats = new JTable(keywordStatsModel);
        tblKeywordStats.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblKeywordStats.setRowHeight(22);
        JScrollPane spKeywords = new JScrollPane(tblKeywordStats);

        // μικρό chart δεξιά του πίνακα (όπως επάνω αριστερά στην εικόνα)
        pnlKeywordBarsSmall = new HorizontalBarsPanel(keywordCounts);
        pnlKeywordBarsSmall.setPreferredSize(new Dimension(260, 180));

        JSplitPane splitTableSmallChart = new JSplitPane(
                JSplitPane.HORIZONTAL_SPLIT,
                spKeywords,
                wrapTitled(pnlKeywordBarsSmall, null)
        );
        splitTableSmallChart.setResizeWeight(0.55);

        // μεγάλο οριζόντιο chart κάτω (όπως κάτω αριστερά στην εικόνα)
        pnlKeywordBarsBig = new HorizontalBarsPanel(keywordCounts);
        pnlKeywordBarsBig.setPreferredSize(new Dimension(10, 230));
        JPanel pnlBigChartBox = wrapTitled(pnlKeywordBarsBig, "Συχνότερες αναζητήσεις (Keywords)");

        JPanel pnlLeftCenter = new JPanel(new BorderLayout(10, 10));
        pnlLeftCenter.add(splitTableSmallChart, BorderLayout.CENTER);
        pnlLeftCenter.add(pnlBigChartBox, BorderLayout.SOUTH);

        pnlLeft.add(pnlLeftCenter, BorderLayout.CENTER);

        // =========================
        // RIGHT panel: Category stats
        // =========================
        JPanel pnlRight = new JPanel(new BorderLayout(10, 10));

        JLabel lblRightTitle = new JLabel("Άρθρα ανά κατηγορία");
        lblRightTitle.setFont(new Font("Arial", Font.PLAIN, 16));
        pnlRight.add(lblRightTitle, BorderLayout.NORTH);

        pnlCategoryPie = new PieChartPanel(categoryCounts);
        pnlCategoryBars = new VerticalBarsPanel(categoryCounts);

        JPanel pnlPieBox = wrapTitled(pnlCategoryPie, null);
        JPanel pnlBarsBox = wrapTitled(pnlCategoryBars, null);

        JSplitPane splitPieBars = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, pnlPieBox, pnlBarsBox);
        splitPieBars.setResizeWeight(0.55);

        // legend table κάτω δεξιά (όπως στην εικόνα)
        categoryLegendModel = new DefaultTableModel(new Object[]{"Κατηγορία", "Articles"}, 0) {
            /**
             * Εδώ υλοποιώ τη μέθοδο <b>isCellEditable()</b>.
             * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
             * @param r Παράμετρος εισόδου.
             * @param c Παράμετρος εισόδου.
             * @return Επιστρέφω αποτέλεσμα.
             */
            @Override public boolean isCellEditable(int r, int c) { return false; }
            /**
             * Εδώ υλοποιώ τη μέθοδο <b>getColumnClass()</b>.
             * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
             * @param columnIndex Παράμετρος εισόδου.
             * @return Επιστρέφω αποτέλεσμα.
             */
            @Override public Class<?> getColumnClass(int columnIndex) {
                return (columnIndex == 1) ? Integer.class : String.class;
            }
        };
        for (Map.Entry<String, Integer> e : categoryCounts.entrySet()) {
            categoryLegendModel.addRow(new Object[]{e.getKey(), e.getValue()});
        }

        tblCategoryLegend = new JTable(categoryLegendModel);
        tblCategoryLegend.setRowHeight(22);
        JScrollPane spLegend = new JScrollPane(tblCategoryLegend);
        spLegend.setPreferredSize(new Dimension(10, 150));

        pnlRight.add(splitPieBars, BorderLayout.CENTER);
        pnlRight.add(spLegend, BorderLayout.SOUTH);

        // =========================
        // MAIN: Left + Right in 2 columns
        // =========================
        JSplitPane splitMain = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, pnlLeft, pnlRight);
        splitMain.setResizeWeight(0.50);

        tabStats.add(splitMain, BorderLayout.CENTER);

        // =========================
        // Bottom line inside Stats tab (όπως στην εικόνα)
        // =========================
        JPanel pnlTabBottom = new JPanel(new BorderLayout());

        lblStatsSelected = new JLabel("Selected: Artificial intelligence");
        lblStatsSelected.setFont(new Font("Arial", Font.PLAIN, 13));

        lblStatsSavedCount = new JLabel("4 saved articles ▼");
        lblStatsSavedCount.setFont(new Font("Arial", Font.PLAIN, 13));

        pnlTabBottom.add(lblStatsSelected, BorderLayout.WEST);
        pnlTabBottom.add(lblStatsSavedCount, BorderLayout.EAST);

        tabStats.add(pnlTabBottom, BorderLayout.SOUTH);

        // =========================
        // Listeners: όταν επιλέγω keyword στο table, ενημερώνω "Selected: ..."
        // =========================
        tblKeywordStats.getSelectionModel().addListSelectionListener(e -> {
            if (e.getValueIsAdjusting()) return;
            int row = tblKeywordStats.getSelectedRow();
            if (row < 0) return;

            String kw = String.valueOf(keywordStatsModel.getValueAt(row, 0));
            lblStatsSelected.setText("Selected: " + kw);

            // ανανεώνω και status bar του frame
            setStatus("Selected keyword: " + kw, false);
        });

        tabStats.revalidate();
        tabStats.repaint();
    }

    /**

     * Εδώ υλοποιώ τη μέθοδο <b>wrapTitled()</b>.

     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

     * @param comp Παράμετρος εισόδου.

     * @param titleOrNull Παράμετρος εισόδου.

     * @return Επιστρέφω αποτέλεσμα.

     */

    private JPanel wrapTitled(JComponent comp, String titleOrNull) {
        JPanel box = new JPanel(new BorderLayout());
        if (titleOrNull != null && !titleOrNull.isBlank()) {
            JLabel lbl = new JLabel(titleOrNull);
            lbl.setFont(new Font("Arial", Font.PLAIN, 14));
            JPanel top = new JPanel(new FlowLayout(FlowLayout.LEFT, 8, 6));
            top.add(lbl);
            box.add(top, BorderLayout.NORTH);
        }
        box.add(comp, BorderLayout.CENTER);
        box.setBorder(BorderFactory.createLineBorder(UIManager.getColor("Component.borderColor")));
        return box;
    }


    // =========================================================
    // Rating stars helper (0..5 -> HTML colored "*****")
    // =========================================================
    /**
     * Εδώ υλοποιώ τη μέθοδο <b>starsHtml()</b>.
     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
     * @param rating Παράμετρος εισόδου.
     * @return Επιστρέφω αποτέλεσμα.
     */
    private String starsHtml(int rating) {
        int r = Math.max(0, Math.min(5, rating));
        StringBuilder sb = new StringBuilder("<html>");
        for (int i = 1; i <= 5; i++) {
            String color = (i <= r) ? "#FFD700" : "#C0C0C0"; // gold / gray
            sb.append("<span style='color:").append(color).append(";'>*</span>");
        }
        sb.append("</html>");
        return sb.toString();
    }

    /**
     * Rating helper (0..5) -> plain text.
     *
     * Used in dialogs (JTextArea) where HTML is not supported.
     * Example: rating=3 => "***.."
     */
    /**
     * Εδώ υλοποιώ τη μέθοδο <b>stars()</b>.
     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
     * @param rating Παράμετρος εισόδου.
     * @return Επιστρέφω αποτέλεσμα.
     */
    private static String stars(int rating) {
        int r = Math.max(0, Math.min(5, rating));
        StringBuilder sb2 = new StringBuilder(5);
        for (int i = 1; i <= 5; i++) sb2.append(i <= r ? "*" : ".");
        return sb2.toString();
    }

    // =========================================================
    // 7.1) Simple charts (χωρίς libraries)
    // =========================================================
/** 
 * Εδώ ορίζω το class <b>HorizontalBarsPanel</b> στο GUI [γραφικό περιβάλλον χρήστη].
 * <p>Στόχος μου είναι να κρατήσω το κομμάτι αυτό καθαρό και καλά σχολιασμένο, ώστε να μπορεί να συνεχίσει εύκολα άλλο μέλος της ομάδας.</p>
 */
    private static class HorizontalBarsPanel extends JPanel {
        private Map<String, Integer> data = new LinkedHashMap<>();

        HorizontalBarsPanel(Map<String, Integer> data) {
            setData(data);
            setBackground(UIManager.getColor("Panel.background"));
        }

        /**

         * Εδώ υλοποιώ τη μέθοδο <b>setData()</b>.

         * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

         * @param Map<String Παράμετρος εισόδου.

         * @param data Παράμετρος εισόδου.

         */

        void setData(Map<String, Integer> data) {
            this.data = new LinkedHashMap<>(data);
            repaint();
        }

        /**

         * Εδώ υλοποιώ τη μέθοδο <b>paintComponent()</b>.

         * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

         * @param g Παράμετρος εισόδου.

         */

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            int w = getWidth();
            int h = getHeight();

            int left = 14;
            int top = 14;
            int right = 14;
            int bottom = 14;

            int innerW = Math.max(1, w - left - right);
            int innerH = Math.max(1, h - top - bottom);

            int n = data.size();
            if (n == 0) { g2.dispose(); return; }

            int max = 1;
            for (int v : data.values()) max = Math.max(max, v);

            int rowH = Math.max(22, innerH / n);
            int y = top;

            for (Map.Entry<String, Integer> e : data.entrySet()) {
                String label = e.getKey();
                int value = e.getValue();

                int barX = left + 120;
                int barW = innerW - 120 - 10;
                int barH = Math.max(10, rowH - 10);

                int fillW = (int) (barW * (value / (double) max));

                // label
                g2.setFont(new Font("Arial", Font.PLAIN, 12));
                g2.setColor(UIManager.getColor("Label.foreground"));
                g2.drawString(label, left, y + 14);

                // bar background
                g2.setColor(UIManager.getColor("Component.borderColor"));
                g2.drawRect(barX, y + 2, barW, barH);

                // bar fill (χρησιμοποιώ UI default χρώμα selection για να μοιάζει με “μπλε”)
                g2.setColor(UIManager.getColor("Table.selectionBackground"));
                g2.fillRect(barX + 1, y + 3, Math.max(0, fillW - 1), Math.max(0, barH - 1));

                // value
                g2.setColor(UIManager.getColor("Label.foreground"));
                g2.drawString(String.valueOf(value), barX + barW + 6, y + 14);

                y += rowH;
            }

            g2.dispose();
        }
    }

/** 

 * Εδώ ορίζω το class <b>VerticalBarsPanel</b> στο GUI [γραφικό περιβάλλον χρήστη].

 * <p>Στόχος μου είναι να κρατήσω το κομμάτι αυτό καθαρό και καλά σχολιασμένο, ώστε να μπορεί να συνεχίσει εύκολα άλλο μέλος της ομάδας.</p>

 */

    private static class VerticalBarsPanel extends JPanel {
        private Map<String, Integer> data = new LinkedHashMap<>();

        VerticalBarsPanel(Map<String, Integer> data) {
            setData(data);
            setBackground(UIManager.getColor("Panel.background"));
        }

        /**

         * Εδώ υλοποιώ τη μέθοδο <b>setData()</b>.

         * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

         * @param Map<String Παράμετρος εισόδου.

         * @param data Παράμετρος εισόδου.

         */

        void setData(Map<String, Integer> data) {
            this.data = new LinkedHashMap<>(data);
            repaint();
        }

        /**

         * Εδώ υλοποιώ τη μέθοδο <b>paintComponent()</b>.

         * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

         * @param g Παράμετρος εισόδου.

         */

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            int w = getWidth();
            int h = getHeight();

            int left = 30;
            int top = 20;
            int right = 16;
            int bottom = 50;

            int innerW = Math.max(1, w - left - right);
            int innerH = Math.max(1, h - top - bottom);

            int n = data.size();
            if (n == 0) { g2.dispose(); return; }

            int max = 1;
            for (int v : data.values()) max = Math.max(max, v);

            // axes
            g2.setColor(UIManager.getColor("Component.borderColor"));
            g2.drawLine(left, top, left, top + innerH);
            g2.drawLine(left, top + innerH, left + innerW, top + innerH);

            int gap = 12;
            int barW = Math.max(18, (innerW - (gap * (n + 1))) / n);

            int i = 0;
            for (Map.Entry<String, Integer> e : data.entrySet()) {
                String label = e.getKey();
                int value = e.getValue();

                int x = left + gap + i * (barW + gap);
                int barH = (int) (innerH * (value / (double) max));
                int y = top + innerH - barH;

                // bar
                g2.setColor(UIManager.getColor("Table.selectionBackground"));
                g2.fillRect(x, y, barW, barH);

                g2.setColor(UIManager.getColor("Component.borderColor"));
                g2.drawRect(x, y, barW, barH);

                // value on top
                g2.setColor(UIManager.getColor("Label.foreground"));
                g2.setFont(new Font("Arial", Font.PLAIN, 12));
                g2.drawString(String.valueOf(value), x + (barW / 2) - 6, y - 6);

                // label bottom (2 lines αν χρειαστεί)
                g2.setFont(new Font("Arial", Font.PLAIN, 12));
                String[] parts = label.split(" ");
                String line1 = (parts.length >= 1) ? parts[0] : label;
                String line2 = (parts.length >= 2) ? parts[1] : "";

                int baseY = top + innerH + 18;
                g2.drawString(line1, x - 4, baseY);
                if (!line2.isBlank()) g2.drawString(line2, x - 4, baseY + 14);

                i++;
            }

            g2.dispose();
        }
    }

/** 

 * Εδώ ορίζω το class <b>PieChartPanel</b> στο GUI [γραφικό περιβάλλον χρήστη].

 * <p>Στόχος μου είναι να κρατήσω το κομμάτι αυτό καθαρό και καλά σχολιασμένο, ώστε να μπορεί να συνεχίσει εύκολα άλλο μέλος της ομάδας.</p>

 */

    private static class PieChartPanel extends JPanel {
        private Map<String, Integer> data = new LinkedHashMap<>();

        PieChartPanel(Map<String, Integer> data) {
            setData(data);
            setBackground(UIManager.getColor("Panel.background"));
        }

        /**

         * Εδώ υλοποιώ τη μέθοδο <b>setData()</b>.

         * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

         * @param Map<String Παράμετρος εισόδου.

         * @param data Παράμετρος εισόδου.

         */

        void setData(Map<String, Integer> data) {
            this.data = new LinkedHashMap<>(data);
            repaint();
        }

        /**

         * Εδώ υλοποιώ τη μέθοδο <b>paintComponent()</b>.

         * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

         * @param g Παράμετρος εισόδου.

         */

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            int w = getWidth();
            int h = getHeight();

            int size = Math.min(w, h) - 30;
            if (size < 40) { g2.dispose(); return; }

            int x = (w - size) / 2;
            int y = (h - size) / 2;

            int total = 0;
            for (int v : data.values()) total += v;
            if (total == 0) { g2.dispose(); return; }

            // “σταθερή” παλέτα με UI-friendly χρώματα (μοιάζει με την εικόνα)
            java.awt.Color[] palette = new java.awt.Color[]{
                    new java.awt.Color(242, 205, 92),
                    new java.awt.Color(224, 122, 95),
                    new java.awt.Color(129, 178, 154),
                    new java.awt.Color(110, 168, 255)
            };

            int start = 90; // ξεκινάω από πάνω (12 η ώρα)
            int i = 0;

            for (Map.Entry<String, Integer> e : data.entrySet()) {
                int value = e.getValue();
                int angle = (int) Math.round(360.0 * value / total);

                g2.setColor(palette[i % palette.length]);
                g2.fillArc(x, y, size, size, start, -angle);

                g2.setColor(UIManager.getColor("Component.borderColor"));
                g2.drawArc(x, y, size, size, start, -angle);

                // label μέσα (percent + articles), όπως στην εικόνα
                double pct = (100.0 * value / total);
                String txt = String.format("%.1f%%\n%d articles", pct, value);

                // πολύ απλή τοποθέτηση: στο κέντρο (δεν είναι τέλειο, αλλά “μοιάζει”)
                if (i == 0) {
                    g2.setColor(UIManager.getColor("Label.foreground"));
                    g2.setFont(new Font("Arial", Font.PLAIN, 12));
                    drawMultiline(g2, txt, x + size / 2 - 25, y + size / 2 - 10);
                }

                start -= angle;
                i++;
            }

            g2.dispose();
        }

        /**

         * Εδώ υλοποιώ τη μέθοδο <b>drawMultiline()</b>.

         * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

         * @param g2 Παράμετρος εισόδου.

         * @param txt Παράμετρος εισόδου.

         * @param x Παράμετρος εισόδου.

         * @param y Παράμετρος εισόδου.

         */

        private void drawMultiline(Graphics2D g2, String txt, int x, int y) {
            String[] lines = txt.split("\n");
            int dy = 0;
            for (String line : lines) {
                g2.drawString(line, x, y + dy);
                dy += 14;
            }
        }
    }

    // =========================================================
    // 8) Dialogs / actions (Search) – placeholders
    // =========================================================
    /**
     * Εδώ υλοποιώ τη μέθοδο <b>showDetailsDialogFromSearch()</b>.
     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
     */
    private void showDetailsDialogFromSearch() {
    Long pageId = getSelectedSearchPageIdOrWarn();
    if (pageId == null) return;
    openArticleDetails(pageId, "Article Details");
}


    /**


     * Εδώ υλοποιώ τη μέθοδο <b>showSaveDialogForSelected()</b>.


     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.


     */


    private void showSaveDialogForSelected() {
        int rowView = tblResults.getSelectedRow();
        if (rowView < 0) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Select a result first.", "No selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int row = tblResults.convertRowIndexToModel(rowView);
        String title = String.valueOf(resultsModel.getValueAt(row, 0));

        JOptionPane.showMessageDialog(this,
                "Save (placeholder)\n\n" + title,
                "Save Article",
                JOptionPane.INFORMATION_MESSAGE);

        setStatus("Saved (placeholder): " + title, false);
    }

    /**

     * Εδώ υλοποιώ τη μέθοδο <b>openInBrowserFromSearch()</b>.

     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

     */

    private void openInBrowserFromSearch() {
        String title = getSelectedSearchTitleOrWarn();
        if (title == null) return;

        int choice = JOptionPane.showConfirmDialog(
                this,
                "Open in browser?\n\n" + title,
                "Open in Browser",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );
        if (choice != JOptionPane.YES_OPTION) {
            setStatus("Open cancelled", false);
            return;
        }

        try {
            String url = "https://en.wikipedia.org/wiki/" + title.trim().replace(" ", "_");
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().browse(new URI(url));
                setStatus("Opened in browser", false);
            } else {
                setStatus("Desktop browse not supported", false);
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Open in browser failed", ex);
            JOptionPane.showMessageDialog(this, "Failed to open browser:\n" + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            setStatus("Open failed", false);
        }
    }

    /**

     * Εδώ υλοποιώ τη μέθοδο <b>getSelectedSearchTitleOrWarn()</b>.

     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

     * @return Επιστρέφω αποτέλεσμα.

     */

    private String getSelectedSearchTitleOrWarn() {
        int rowView = tblResults.getSelectedRow();
        if (rowView < 0) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Select a result first.", "No selection", JOptionPane.WARNING_MESSAGE);
            setStatus("No selection", false);
            return null;
        }
        int row = tblResults.convertRowIndexToModel(rowView);
        return String.valueOf(resultsModel.getValueAt(row, 0));
    }

    // =========================================================
    // 9) Dialogs / actions (Saved) – placeholders
    // =========================================================
    /**
     * Εδώ υλοποιώ τη μέθοδο <b>showLoadDialogFromSaved()</b>.
     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
     */
    private void showLoadDialogFromSaved() {
    Long pageId = getSelectedSavedPageIdOrWarn();
    if (pageId == null) return;
    openArticleDetails(pageId, "Saved Article");
}


    /**


     * Εδώ υλοποιώ τη μέθοδο <b>deleteSelectedSaved()</b>.


     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.


     */


    private void deleteSelectedSaved() {
        int rowView = tblSaved.getSelectedRow();
        if (rowView < 0) {
            Toolkit.getDefaultToolkit().beep();
            setStatus("No saved selection", false);
            return;
        }

        int row = tblSaved.convertRowIndexToModel(rowView);
        String title = String.valueOf(savedModel.getValueAt(row, 0));
        long pageId = Long.parseLong(String.valueOf(savedModel.getValueAt(row, 1)));

        int choice = JOptionPane.showConfirmDialog(
                this,
                "Delete saved article?\n\n" + title,
                "Delete",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );
        if (choice != JOptionPane.YES_OPTION) {
            setStatus("Delete cancelled", false);
            return;
        }

        setStatus("Deleting…", true);
        new SwingWorker<Void, Void>() {
            /**
             * Εδώ υλοποιώ τη μέθοδο <b>doInBackground()</b>.
             * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
             * @return Επιστρέφω αποτέλεσμα.
             */
            @Override
            protected Void doInBackground() {
                controller.deleteSaved(pageId);
                return null;
            }

            /**

             * Εδώ υλοποιώ τη μέθοδο <b>done()</b>.

             * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

             */

            @Override
            protected void done() {
                refreshSavedInBackground();
                refreshStatsInBackground();
                txtSavedPreview.setText("Title:\n\nPreview κειμένου (placeholder)…");
                setStatus("Deleted: " + title, false);
            }
        }.execute();
    }

    /**

     * Εδώ υλοποιώ τη μέθοδο <b>clearAllSaved()</b>.

     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

     */

    private void clearAllSaved() {
        if (savedModel.getRowCount() == 0) {
            setStatus("Saved list already empty", false);
            return;
        }

        int choice = JOptionPane.showConfirmDialog(
                this,
                "Clear the entire saved list?",
                "Clear List",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );
        if (choice != JOptionPane.YES_OPTION) {
            setStatus("Clear cancelled", false);
            return;
        }

        setStatus("Clearing saved list…", true);
        new SwingWorker<Void, Void>() {
            /**
             * Εδώ υλοποιώ τη μέθοδο <b>doInBackground()</b>.
             * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
             * @return Επιστρέφω αποτέλεσμα.
             */
            @Override
            protected Void doInBackground() {
                controller.clearAllSaved();
                return null;
            }

            /**

             * Εδώ υλοποιώ τη μέθοδο <b>done()</b>.

             * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

             */

            @Override
            protected void done() {
                refreshSavedInBackground();
                refreshStatsInBackground();
                txtSavedPreview.setText("Title:\n\nPreview κειμένου (placeholder)…");
                setStatus("Saved list cleared", false);
            }
        }.execute();
    }

    // =========================================================
    // 10) Search behavior (DB/API mode – placeholder)
    // =========================================================
    /**
     * Εδώ υλοποιώ τη μέθοδο <b>onSearch()</b>.
     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
     */
    private void onSearch() {
        String q = (txtKeywords.getText() == null) ? "" : txtKeywords.getText().trim();
        if (q.isEmpty()) {
            Toolkit.getDefaultToolkit().beep();
            setStatus("Enter keywords…", false);
            return;
        }

        String mode = (bgSearchMode.getSelection() != null)
                ? bgSearchMode.getSelection().getActionCommand()
                : "DB_API";

        SearchMode searchMode;
        try {
            searchMode = SearchMode.valueOf(mode);
        } catch (Exception ex) {
            searchMode = SearchMode.DB_API;
        }

        final SearchMode modeFinal = searchMode;
        setStatus("Searching… (" + modeFinal + ") for: " + q, true);

        // SwingWorker = background thread (δεν παγώνει το EDT)
        new SwingWorker<List<SearchResultRow>, Void>() {
            /**
             * Εδώ υλοποιώ τη μέθοδο <b>doInBackground()</b>.
             * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
             * @return Επιστρέφω αποτέλεσμα.
             */
            @Override
            protected List<SearchResultRow> doInBackground() {
                return controller.search(q, modeFinal, getCheckedCategories());
            }

            /**

             * Εδώ υλοποιώ τη μέθοδο <b>done()</b>.

             * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

             */

            @Override
            protected void done() {
                try {
                    setSearchResults(get());
                    setStatus("Found results for: " + q, false);
                } catch (Exception ex) {
                    logger.log(java.util.logging.Level.SEVERE, "Search failed", ex);
                    JOptionPane.showMessageDialog(MainFrame.this,
                            "Search failed:\n" + ex.getMessage(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                    setStatus("Search failed", false);
                }
            }
        }.execute();
    }

    /**

     * Εδώ υλοποιώ τη μέθοδο <b>clearSearchUI()</b>.

     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

     */

    private void clearSearchUI() {
        txtKeywords.setText("");
        rbDbApi.setSelected(true);

        // Καθαρίζω αποτελέσματα (πλέον έρχονται από Controller, όχι dummy στο GUI)
        if (resultsModel != null) resultsModel.setRowCount(0);

        if (tblResults != null) tblResults.clearSelection();
        if (txtPreview != null) txtPreview.setText("Preview κειμένου (placeholder)…");

        if (sldSearchRating != null) sldSearchRating.setValue(0);
        if (txtSearchComments != null) txtSearchComments.setText("");

        setStatus("Ready", false);
        txtKeywords.requestFocusInWindow();
    }

    // =========================================================
    // 11) Status + menu nav
    // =========================================================
    /**
     * Εδώ υλοποιώ τη μέθοδο <b>buildStatusBar()</b>.
     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
     */
    private void buildStatusBar() {
        JPanel pnlStatus = new JPanel(new BorderLayout());

        progress = new JProgressBar();
        progress.setIndeterminate(true);
        progress.setVisible(false);

        lblStatus = new JLabel("Ready");
        lblStatus.setFont(new Font("Arial", Font.PLAIN, 12));

        pnlStatus.add(progress, BorderLayout.WEST);
        pnlStatus.add(lblStatus, BorderLayout.EAST);

        getContentPane().add(pnlStatus, BorderLayout.PAGE_END);
        getContentPane().revalidate();
        getContentPane().repaint();
    }

    /**

     * Εδώ υλοποιώ τη μέθοδο <b>setStatus()</b>.

     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

     * @param msg Παράμετρος εισόδου.

     * @param busy Παράμετρος εισόδου.

     */

    private void setStatus(String msg, boolean busy) {
        if (lblStatus != null) lblStatus.setText(msg);
        if (progress != null) progress.setVisible(busy);
    }

    /**

     * Εδώ υλοποιώ τη μέθοδο <b>wireMenuNavigation()</b>.

     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

     */

    private void wireMenuNavigation() {
        miOpenSavedTab.addActionListener(e -> { tabsMain.setSelectedComponent(tabSaved); reloadSavedArticles(); });
        miOpenStatsTab.addActionListener(e -> tabsMain.setSelectedComponent(tabStats));
    }

    // =========================================================
    // 12) New category prompt (κοινό)
    // =========================================================
    /**
     * Εδώ υλοποιώ τη μέθοδο <b>promptNewCategory()</b>.
     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
     */
    private void promptNewCategory() {
        String n = JOptionPane.showInputDialog(
                this,
                "Δώσε νέα κατηγορία:",
                "Νέα Κατηγορία",
                JOptionPane.QUESTION_MESSAGE
        );
        addNewCategoryFromUser(n);
    }

    // =========================================================
    // 13) Custom checkbox list (JList with checkbox renderer)
    // =========================================================
/** 
 * Εδώ ορίζω το class <b>CategoryCheckList</b> στο GUI [γραφικό περιβάλλον χρήστη].
 * <p>Στόχος μου είναι να κρατήσω το κομμάτι αυτό καθαρό και καλά σχολιασμένο, ώστε να μπορεί να συνεχίσει εύκολα άλλο μέλος της ομάδας.</p>
 */
    private class CategoryCheckList extends JList<String> {
        private Runnable onSelectionChanged;

        CategoryCheckList(String tooltip) {
            super();
            setToolTipText(tooltip);

            setCellRenderer((list, value, index, isSelected, cellHasFocus) -> {
                JCheckBox cb = new JCheckBox(value);
                cb.setFont(new Font("Arial", Font.PLAIN, 13));
                cb.setOpaque(true);
                cb.setSelected(Boolean.TRUE.equals(categoryChecked.get(value)));

                cb.setBackground(isSelected ? list.getSelectionBackground() : list.getBackground());
                cb.setForeground(isSelected ? list.getSelectionForeground() : list.getForeground());
                return cb;
            });

            refreshFromModel();

            // Με click πάνω στο item κάνω toggle checked.
            addMouseListener(new MouseAdapter() {
                /**
                 * Εδώ υλοποιώ τη μέθοδο <b>mouseClicked()</b>.
                 * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
                 * @param e Παράμετρος εισόδου.
                 */
                @Override
                public void mouseClicked(MouseEvent e) {
                    int idx = locationToIndex(e.getPoint());
                    if (idx < 0) return;

                    String name = getModel().getElementAt(idx);
                    boolean newVal = !Boolean.TRUE.equals(categoryChecked.get(name));

                    // Αν τσεκάρω “Όλες οι κατηγορίες”, ξε-τσεκάρω τα υπόλοιπα.
                    if ("Όλες οι κατηγορίες".equals(name) && newVal) {
                        for (String k : categoryChecked.keySet()) categoryChecked.put(k, false);
                        categoryChecked.put(name, true);
                    } else {
                        if (newVal) categoryChecked.put("Όλες οι κατηγορίες", false);
                        categoryChecked.put(name, newVal);
                    }

                    repaint();

                    if (onSelectionChanged != null) onSelectionChanged.run();
                }
            });
        }

        /**

         * Εδώ υλοποιώ τη μέθοδο <b>setOnSelectionChanged()</b>.

         * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

         * @param r Παράμετρος εισόδου.

         */

        void setOnSelectionChanged(Runnable r) {
            this.onSelectionChanged = r;
        }

        /**

         * Εδώ υλοποιώ τη μέθοδο <b>refreshFromModel()</b>.

         * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.

         */

        void refreshFromModel() {
            DefaultListModel<String> lm = new DefaultListModel<>();
            for (int i = 0; i < categoriesComboModel.getSize(); i++) {
                lm.addElement(categoriesComboModel.getElementAt(i));
            }
            setModel(lm);
            repaint();
        }
    }







    
    /**







    
     * Εδώ υλοποιώ τη μέθοδο <b>miExitActionPerformed()</b>.







    
     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.







    
     * @param evt Παράμετρος εισόδου.







    
     */







    
    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        // TODO add your handling code here:
         dispose(); // κλείνει το MainFrame (close frame)
    }//GEN-LAST:event_miExitActionPerformed
    // (ΣΗΜΕΙΩΣΗ) Το handler του μενού “Clear Search” βρίσκεται πιο κάτω, ώστε να μην υπάρχει διπλο-ορισμός.
    // =========================================================
    // 14) Missing helper methods – needed by the current GUI code
    // =========================================================

    /**
     * Επαναφόρτωση Saved articles από τον Controller.
     * (Καλείται όταν αλλάζει το φίλτρο κατηγοριών ή μετά από ενέργειες Delete/Clear.)
     */
    /**
     * Εδώ υλοποιώ τη μέθοδο <b>reloadSavedArticles()</b>.
     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
     */
    private void reloadSavedArticles() {
        // Χρησιμοποιούμε την ήδη υπάρχουσα «σωστή» ροή με SwingWorker,
        // ώστε το GUI να μην παγώνει.
        refreshSavedInBackground();
    }

    /**
     * Ξανατρέχει Search με το τρέχον query στο txtKeywords.
     */
    /**
     * Εδώ υλοποιώ τη μέθοδο <b>reloadSearchWithCurrentQuery()</b>.
     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
     */
    private void reloadSearchWithCurrentQuery() {
        onSearch();
    }

    /**
     * Φορτώνει/δείχνει metadata (rating/comments/categories) για ένα Saved article.
     *
     * Στο dummy στάδιο, τα metadata έρχονται μέσα στο SavedArticleRow.
     *
     * ==TO DO : Όταν τα metadata μεταφερθούν σε ξεχωριστό Entity/DB table,
     *           πρόσθεσε στον Controller μέθοδο π.χ. getSavedMetadata(pageId)
     *           και εδώ κάλεσέ την, ώστε το GUI να μην κάνει "data mining" από πίνακες.
     */
    /**
     * Εδώ υλοποιώ τη μέθοδο <b>loadSavedMetadata()</b>.
     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
     * @param pageId Παράμετρος εισόδου.
     */
    private void loadSavedMetadata(long pageId) {
        // Βρίσκω τη γραμμή μέσα στο JTable model και ενημερώνω τα πεδία UI.
        for (int r = 0; r < savedModel.getRowCount(); r++) {
            Object v = savedModel.getValueAt(r, 1); // PageId
            if (v instanceof Number && ((Number) v).longValue() == pageId) {
                // Columns: Title, PageId, SavedAt, Source, Categories, Rating, Comments
                Object categories = savedModel.getValueAt(r, 4);
                Object rating = savedModel.getValueAt(r, 5);
                Object comments = savedModel.getValueAt(r, 6);

//                 if (lblSavedCategories != null) lblSavedCategories.setText(String.valueOf(categories));
//                 if (lblSavedRating != null) lblSavedRating.setText(String.valueOf(rating));
                if (txtSavedComments != null) txtSavedComments.setText(String.valueOf(comments));
                return;
            }
        }
    }

    /** Παίρνει PageId από το επιλεγμένο row στον Search results table. */
    private Long getSelectedSearchPageIdOrWarn() {
        int rowView = (tblResults == null) ? -1 : tblResults.getSelectedRow();
        if (rowView < 0) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Select a result first.", "No selection", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        int row = tblResults.convertRowIndexToModel(rowView);
        Object v = resultsModel.getValueAt(row, 3); // PageId (hidden)
        if (v instanceof Number) return ((Number) v).longValue();
        try {
            return Long.valueOf(String.valueOf(v));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Invalid PageId.", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }

    /** Παίρνει PageId από το επιλεγμένο row στον Saved table. */
    private Long getSelectedSavedPageIdOrWarn() {
        int rowView = (tblSaved == null) ? -1 : tblSaved.getSelectedRow();
        if (rowView < 0) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Select a saved article first.", "No selection", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        int row = tblSaved.convertRowIndexToModel(rowView);
        Object v = savedModel.getValueAt(row, 1); // PageId
        if (v instanceof Number) return ((Number) v).longValue();
        try {
            return Long.valueOf(String.valueOf(v));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Invalid PageId.", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }

    /**
     * Εμφανίζει Article Details σε μεγάλο παράθυρο (≈80% οθόνης) με scroll.
     * modeHint: "Search" ή "Saved" απλά για logging/UI.
     */
    /**
     * Εδώ υλοποιώ τη μέθοδο <b>openArticleDetails()</b>.
     * Τη χρησιμοποιώ για να εκτελέσω τη συγκεκριμένη λειτουργία με ασφαλή τρόπο.
     * @param pageId Παράμετρος εισόδου.
     * @param modeHint Παράμετρος εισόδου.
     */
    private void openArticleDetails(Long pageId, String modeHint) {
        if (pageId == null) return;

        ArticleDetails d = controller.getDetails(pageId);

        JDialog dlg = new JDialog(this, "Article Details", true);
        dlg.setLayout(new BorderLayout(10, 10));

        JTextArea area = new JTextArea();
        area.setEditable(false);
        area.setLineWrap(true);
        area.setWrapStyleWord(true);
        area.setFont(new Font("Arial", Font.PLAIN, 13));
        area.setMargin(new Insets(12, 12, 12, 12));

        area.setText(
                "Title: " + d.title() + "\n" +
                "PageId: " + d.pageId() + "\n" +
                "Source: " + d.source() + "\n" +
                "Categories: " + formatCategories(d.categories()) + "\n" +
                "Rating: " + stars(d.rating()) + "\n" +
                "Comments: " + (d.comments() == null ? "" : d.comments()) + "\n" +
                "\n" +
                d.fullText()
        );

        JScrollPane sp = new JScrollPane(area);
        dlg.add(sp, BorderLayout.CENTER);

        // Bottom buttons
        JButton btnPrint = new JButton("Print Local Printer");
        JButton btnSave = new JButton("Save Local Disk");
        JButton btnClose = new JButton("Close");

        btnClose.addActionListener(e -> dlg.dispose());

        // Stub dialogs (όχι πραγματικό PDF/DOCX εδώ)
        btnPrint.addActionListener(e -> {
            Object[] options = {"PDF", "DOCX", "Cancel"};
            int choice = JOptionPane.showOptionDialog(
                    dlg,
                    "Print as:",
                    "Print",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[0]
            );
            if (choice == 0) JOptionPane.showMessageDialog(dlg, "(Stub) Print to PDF...", "Print", JOptionPane.INFORMATION_MESSAGE);
            else if (choice == 1) JOptionPane.showMessageDialog(dlg, "(Stub) Print to DOCX...", "Print", JOptionPane.INFORMATION_MESSAGE);
        });

        btnSave.addActionListener(e -> {
            Object[] options = {"PDF", "DOCX", "Cancel"};
            int choice = JOptionPane.showOptionDialog(
                    dlg,
                    "Save as:",
                    "Save",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[0]
            );
            if (choice == 0) JOptionPane.showMessageDialog(dlg, "(Stub) Save PDF...", "Save", JOptionPane.INFORMATION_MESSAGE);
            else if (choice == 1) JOptionPane.showMessageDialog(dlg, "(Stub) Save DOCX...", "Save", JOptionPane.INFORMATION_MESSAGE);
        });

        JPanel bottom = new JPanel(new FlowLayout(FlowLayout.RIGHT, 10, 8));
        bottom.add(btnPrint);
        bottom.add(btnSave);
        bottom.add(btnClose);
        dlg.add(bottom, BorderLayout.SOUTH);

        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        dlg.setSize((int) (screen.width * 0.80), (int) (screen.height * 0.80));
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);

        setStatus("Closed details (" + modeHint + ")", false);
    }

    // Handler [χειριστής] για το μενού: File -> Clear Search
    // (Εδώ δεν βάζω demo println. Καλώ την πραγματική μέθοδο καθαρισμού.)
private void miClearSearchActionPerformed(java.awt.event.ActionEvent evt) {
    if (txtKeywords == null) return; // postInit δεν έχει τρέξει ακόμη
    clearSearchUI();
}

    // =========================================================
    // 14) Missing helper methods – needed by the current GUI code
    // =========================================================

    /**
     * Επαναφόρτωση Saved articles από τον Controller.
     * (Καλείται όταν αλλάζει το φίλτρο κατηγοριών ή μετά από ενέργειες Delete/Clear.)
     */

/*Δεν μπορώ να τον διαγράψω είναι binding sto menoy File παραμένει εντός σχολίων
ισχύει ο από eπανω δεν τρέχει αυτός
    private void miClearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClearSearchActionPerformed
        // TODO add your handling code here:
        System.out.println("Clear Search clicked");
    }//GEN-LAST:event_miClearSearchActionPerformed
*/
    /**
     * @param args the command line arguments
     */
    
    // NOTE: Η εφαρμογή εκκινεί από packageMain/App.java.

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenu menuExit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuSaved;
    private javax.swing.JMenu menuStats;
    private javax.swing.JMenuItem miClearSearch;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miOpenSavedTab;
    private javax.swing.JMenuItem miOpenStatsTab;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JPanel tabSaved;
    private javax.swing.JPanel tabSearch;
    private javax.swing.JPanel tabStats;
    private javax.swing.JTabbedPane tabsMain;
    // End of variables declaration//GEN-END:variables

}