
package com.plh24.packageGUI;


public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        tabsMain = new javax.swing.JTabbedPane();
        tabSearch = new javax.swing.JPanel();
        tabSaved = new javax.swing.JPanel();
        tabStats = new javax.swing.JPanel();
        mainMenuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        miClearSearch = new javax.swing.JMenuItem();
        menuSaved = new javax.swing.JMenu();
        miOpenSavedTab = new javax.swing.JMenuItem();
        menuStats = new javax.swing.JMenu();
        miOpenStatsTab = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenu();
        miExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Καρτέλα Επιλογών WiKi");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Keywords");

        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Search");

        jCheckBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox1.setText("DB only");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox2.setText("DB/API");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addGap(42, 42, 42)
                .addComponent(jCheckBox1)
                .addGap(31, 31, 31)
                .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tabsMain.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout tabSearchLayout = new javax.swing.GroupLayout(tabSearch);
        tabSearch.setLayout(tabSearchLayout);
        tabSearchLayout.setHorizontalGroup(
            tabSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        tabSearchLayout.setVerticalGroup(
            tabSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        tabsMain.addTab("Search Articles", tabSearch);
        tabSearch.getAccessibleContext().setAccessibleName("tabSearch");

        javax.swing.GroupLayout tabSavedLayout = new javax.swing.GroupLayout(tabSaved);
        tabSaved.setLayout(tabSavedLayout);
        tabSavedLayout.setHorizontalGroup(
            tabSavedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        tabSavedLayout.setVerticalGroup(
            tabSavedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        tabsMain.addTab("Saved Articles", tabSaved);
        tabSaved.getAccessibleContext().setAccessibleName("tabSaved");
        tabSaved.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout tabStatsLayout = new javax.swing.GroupLayout(tabStats);
        tabStats.setLayout(tabStatsLayout);
        tabStatsLayout.setHorizontalGroup(
            tabStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        tabStatsLayout.setVerticalGroup(
            tabStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        tabsMain.addTab("Stats & Keywords", tabStats);
        tabStats.getAccessibleContext().setAccessibleName("tabStats");

        getContentPane().add(tabsMain, java.awt.BorderLayout.CENTER);
        tabsMain.getAccessibleContext().setAccessibleName("tabsMain");
        tabsMain.getAccessibleContext().setAccessibleDescription("");

        mainMenuBar.setToolTipText("");
        mainMenuBar.setName("Καρτέλα Επιλογών WiKi"); // NOI18N

        menuFile.setText("File");
        menuFile.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        miClearSearch.setText("Clear Search");
        miClearSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClearSearchActionPerformed(evt);
            }
        });
        menuFile.add(miClearSearch);
        miClearSearch.getAccessibleContext().setAccessibleName("miClearSearch");
        miClearSearch.getAccessibleContext().setAccessibleDescription("");

        mainMenuBar.add(menuFile);
        menuFile.getAccessibleContext().setAccessibleName("menuFile");

        menuSaved.setText("Saved");
        menuSaved.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        miOpenSavedTab.setText("Saved Articles");
        menuSaved.add(miOpenSavedTab);
        miOpenSavedTab.getAccessibleContext().setAccessibleName("miOpenSavedTab");

        mainMenuBar.add(menuSaved);
        menuSaved.getAccessibleContext().setAccessibleName("menuSaved");

        menuStats.setText("Stats");
        menuStats.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        miOpenStatsTab.setText("Statistics");
        menuStats.add(miOpenStatsTab);
        miOpenStatsTab.getAccessibleContext().setAccessibleName("miOpenStatsTab");

        mainMenuBar.add(menuStats);
        menuStats.getAccessibleContext().setAccessibleName("menuStats");

        menuExit.setText("Exit");
        menuExit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        menuExit.add(miExit);
        miExit.getAccessibleContext().setAccessibleName("miExit");
        miExit.getAccessibleContext().setAccessibleDescription("");

        mainMenuBar.add(menuExit);
        menuExit.getAccessibleContext().setAccessibleName("menuExit");

        setJMenuBar(mainMenuBar);
        mainMenuBar.getAccessibleContext().setAccessibleName("mainMenuBar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        // TODO add your handling code here:
         dispose(); // κλείνει το MainFrame (close frame)
    }//GEN-LAST:event_miExitActionPerformed

    private void miClearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClearSearchActionPerformed
        // TODO add your handling code here:
        System.out.println("Clear Search clicked");
    }//GEN-LAST:event_miClearSearchActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenu menuExit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuSaved;
    private javax.swing.JMenu menuStats;
    private javax.swing.JMenuItem miClearSearch;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miOpenSavedTab;
    private javax.swing.JMenuItem miOpenStatsTab;
    private javax.swing.JPanel tabSaved;
    private javax.swing.JPanel tabSearch;
    private javax.swing.JPanel tabStats;
    private javax.swing.JTabbedPane tabsMain;
    // End of variables declaration//GEN-END:variables
}
