/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.plh24.packageGUI;

import com.plh24.packageEntities.Article;
import com.plh24.packageUtils.Utilities;
import java.util.List;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import javax.swing.DefaultListModel;



/**
 *
 * @author Equinox
 */
public class ViewByCategoryPanel extends javax.swing.JPanel {
    private EntityManagerFactory emf = null;

    private synchronized EntityManagerFactory getEmf() {
        if (emf == null) {
            if (java.beans.Beans.isDesignTime()) return null;
            emf = Persistence.createEntityManagerFactory("EapWikiPU");
        }
        return emf;
    }
    
    
    /**
     * Creates new form ViewByCategoryPanel
     */
    public ViewByCategoryPanel() {
        initComponents();
        Utilities.updateCategoriesComboBox(categorySearchBox, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        categorySearchBox = new javax.swing.JComboBox<>();
        showCategoryArticlesBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        articleTitleByCategory = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        jLabel1.setText("Κατηγορίες");

        showCategoryArticlesBtn.setText("Εμφάνιση Άρθρων");
        showCategoryArticlesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCategoryArticlesBtnActionPerformed(evt);
            }
        });

        articleTitleByCategory.setEditable(false);
        articleTitleByCategory.setFocusable(false);
        jScrollPane1.setViewportView(articleTitleByCategory);

        jLabel2.setText("Τίτλοι Άρθρων Ανά Κατηγορία");

        jList1.setToolTipText("");
        jList1.setAutoscrolls(false);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(showCategoryArticlesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(categorySearchBox, 0, 212, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(categorySearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(showCategoryArticlesBtn)
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    //Όταν πατηθεί το κουμπί καλείται
    private void showCategoryArticlesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCategoryArticlesBtnActionPerformed
    String selectedCategory =
            categorySearchBox.getSelectedItem().toString(); //πέρνει την επιλεγμένη κατηγορία απο ComboBox

   
    EntityManagerFactory localEmf = getEmf();
    if (localEmf == null) return; // design-time or cannot create EMF

    EntityManager em = localEmf.createEntityManager();//δημιουργεί σύνδεση με βάση

    try {

        List<Article> articles = em.createQuery(//φέρε όλα τα άθρα που η κατηγορία ταιριάζει, ταξινόμηση με βάση το τιτλο
                "SELECT a FROM Article a WHERE a.category.name = :cat ORDER BY a.title",
                Article.class)
                .setParameter("cat", selectedCategory)
                .getResultList();

        //δημιουργία μοντέλου JList
        DefaultListModel<String> model = new DefaultListModel<>();

        //δημιουργία κειμένου στο δεξί panel
        StringBuilder sb = new StringBuilder();
        sb.append("Κατηγορία: ").append(selectedCategory).append("\n\n");

        
        for (Article a : articles) {
            model.addElement(a.getTitle());        //για το scrollDown
            sb.append("• ").append(a.getTitle()).append("\n\n");  // για το δεξί πλαίσιο
        }

        //Εμφάνιση δεδομένων
        jList1.setModel(model);
        articleTitleByCategory.setText(sb.toString());

    } catch (Exception e) {
        e.printStackTrace();
    } finally {
        if (em != null && em.isOpen()) em.close();//κλείσιμο συνδεσης με βάση
    }  
    }//GEN-LAST:event_showCategoryArticlesBtnActionPerformed

    
    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {// Διπλό κλικ σε ένα άθρο 

        String selectedTitle = jList1.getSelectedValue();//πείρνει τον επιλεγμένο τίτλο

        if (selectedTitle != null) {
            
            //βρίσκει το κύριο Frame
            MainFrame mf =
                (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

            mf.updateViewAndSwitch(selectedTitle);//πάνε στο ViewFrame και φόρτωσε το άθρο με αυτό το τίτλο
        }
      }
    }//GEN-LAST:event_jList1MouseClicked

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane articleTitleByCategory;
    private javax.swing.JComboBox<String> categorySearchBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton showCategoryArticlesBtn;
    // End of variables declaration//GEN-END:variables

}
