/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package packageGUI;
import static packageAPI.APIMain.parseAndPrintResults;
import static packageAPI.APIMain.parsearticlefetch;
import static packageAPI.APIMain.stripSnippetHTMLTags;
import packageAPI.WikiApiClient;
import java.io.IOException;
import org.json.JSONArray;
import org.json.JSONObject;
import java.awt.Color;

/**
 *
 * @author Equinox
 */
public class ArticleSearchPanel extends javax.swing.JPanel {
    private final packageController.Controller.WikiController controller;
    private final java.util.Map<String, Long> titleToPageId = new java.util.HashMap<>();

    /**
     * Creates new form SearchPanel
     */
public ArticleSearchPanel(packageController.Controller.WikiController controller) {
    this.controller = controller;
    initComponents();

    btnViewArticle.setEnabled(false);
    btnSaveArticle.setEnabled(false);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSearch = new javax.swing.JLabel();
        searchInputField = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        scrollResults = new javax.swing.JScrollPane();
        searchResultOutput = new javax.swing.JTextPane();
        lblResults = new javax.swing.JLabel();
        lblSelectArticle = new javax.swing.JLabel();
        titleComboBox = new javax.swing.JComboBox<>();
        btnViewArticle = new javax.swing.JButton();
        btnSaveArticle = new javax.swing.JButton();

        lblSearch.setText("Αναζήτηση:");

        searchInputField.setForeground(new java.awt.Color(153, 153, 153));
        searchInputField.setText("Αναζήτηση Εδώ");
        searchInputField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchInputFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchInputFieldFocusLost(evt);
            }
        });

        btnSearch.setText("Αναζήτηση");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        searchResultOutput.setEditable(false);
        searchResultOutput.setFocusable(false);
        scrollResults.setViewportView(searchResultOutput);

        lblResults.setText("Αποτελέσματα:");

        lblSelectArticle.setText("Επιλογή Άρθρου:");

        titleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Επιλέξτε ---" }));

        btnViewArticle.setText("Προβολή Άρθρου");
        btnViewArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewArticleActionPerformed(evt);
            }
        });

        btnSaveArticle.setText("Αποθήκευση Άρθρου");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewArticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSaveArticle, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(searchInputField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSearch)
                            .addComponent(lblSelectArticle))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollResults, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResults))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch)
                    .addComponent(lblResults))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)
                        .addGap(18, 18, 18)
                        .addComponent(lblSelectArticle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewArticle)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveArticle))
                    .addComponent(scrollResults, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
String keyword = searchInputField.getText().trim();
    if (keyword.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Δώσε λέξη-κλειδί.");
        return;
    }
    runSearchInBackground(keyword);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnViewArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewArticleActionPerformed
        // TODO add your handling code here:
        String selectedTitle = titleComboBox.getSelectedItem().toString();
//        javax.swing.JTabbedPane tabbedPanel = (javax.swing.JTabbedPane) this.getParent().getParent();
//        tabbedPanel.setSelectedIndex(1);
        MainFrame mf = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        mf.updateViewAndSwitch(selectedTitle);
    }//GEN-LAST:event_btnViewArticleActionPerformed

    private void searchInputFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchInputFieldFocusGained
        // TODO add your handling code here:
        if (searchInputField.getText().equals("Αναζήτηση Εδώ")){
            searchInputField.setText("");
            searchInputField.setForeground(new Color (0,0,0));
        }
    }//GEN-LAST:event_searchInputFieldFocusGained

    private void searchInputFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchInputFieldFocusLost
        // TODO add your handling code here:
        if (searchInputField.getText().equals("")){
            searchInputField.setText("Αναζήτηση Εδώ");
            searchInputField.setForeground(new Color (153,153,153));
        }
            
    }//GEN-LAST:event_searchInputFieldFocusLost

        private void runSearchInBackground(String keyword) {
            if (controller == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Controller δεν έχει αρχικοποιηθεί.");
                return;
            }
            btnSearch.setEnabled(false);
            btnViewArticle.setEnabled(false);
            btnSaveArticle.setEnabled(false);
            titleComboBox.removeAllItems();
            searchResultOutput.setText("Searching for: " + keyword + " ...");
            new javax.swing.SwingWorker<SearchUiPayload, Void>() {
                @Override
                protected SearchUiPayload doInBackground() throws Exception {
                    WikiApiClient api = new WikiApiClient();
                    String jsonResponse = api.searchWikipedia(keyword);
                    
            JSONObject obj = new JSONObject(jsonResponse);
            JSONObject query = obj.getJSONObject("query");
            JSONArray searchResults = query.getJSONArray("search");

            java.util.List<String> titles = new java.util.ArrayList<>();
            StringBuilder output = new StringBuilder();

            output.append("Αποτελέσματα για: ").append(keyword).append("\n");
            output.append("Βρέθηκαν: ").append(searchResults.length()).append("\n\n");

            for (int i = 0; i < searchResults.length(); i++) {
                JSONObject item = searchResults.getJSONObject(i);
                String title = item.getString("title");
                int wordCount = item.optInt("wordcount", 0);

                titles.add(title);

                output.append(i + 1).append(". ").append(title)
                      .append(" (").append(wordCount).append(" λέξεις)").append("\n")
                      .append("\tΤμήμα: \"...")
                      .append(stripSnippetHTMLTags(item.optString("snippet", "")))
                      .append("...\"")
                      .append("\n\n");
            }

            return new SearchUiPayload(titles, output.toString());
        }

        @Override
        protected void done() {
            try {
                SearchUiPayload payload = get();

                // Γέμισμα combo
                titleComboBox.addItem("--- Επιλέξτε ---");
                for (String t : payload.titles) {
                    titleComboBox.addItem(t);
                }

                // Γέμισμα output
                searchResultOutput.setText(payload.outputText);

                boolean has = !payload.titles.isEmpty();
                btnViewArticle.setEnabled(has);
                btnSaveArticle.setEnabled(has);

            } catch (Exception ex) {
                searchResultOutput.setText("API Error: " + ex.getMessage());
                javax.swing.JOptionPane.showMessageDialog(
                        ArticleSearchPanel.this,
                        "Σφάλμα αναζήτησης: " + ex.getMessage(),
                        "API Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                );
            } finally {
                btnSearch.setEnabled(true);
            }
        }
    }.execute();
}

// Μικρό “πακέτο” επιστροφής για UI
private static final class SearchUiPayload {
    final java.util.List<String> titles;
    final String outputText;
    SearchUiPayload(java.util.List<String> titles, String outputText) {
        this.titles = titles;
        this.outputText = outputText;
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveArticle;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewArticle;
    private javax.swing.JLabel lblResults;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSelectArticle;
    private javax.swing.JScrollPane scrollResults;
    private javax.swing.JTextField searchInputField;
    private javax.swing.JTextPane searchResultOutput;
    private javax.swing.JComboBox<String> titleComboBox;
    // End of variables declaration//GEN-END:variables

}
