/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packageGUI;

import packageEntities.Category;
import java.util.List;
import java.util.ArrayList;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import jakarta.persistence.Query;

/**
 *
 * @author Equinox
 */

public class MainFrame extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(MainFrame.class.getName());

    private java.util.List<Category> categoriesList = new java.util.ArrayList<>();
    private ArticleViewPanel viewPanel;
    private ArticleSearchPanel searchPanel;
    private ArticlesByCategoryPanel byCategoryPanel;
    private StatsPanel statsPanel;
    
    private final packageController.Controller.WikiController controller =
        new packageController.Controller.WikiControllerImpl();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        wirePanels();
        loadCategoriesAsync();
    }

private void wirePanels() {
    
    // Δημιουργία panels
    searchPanel = new ArticleSearchPanel(controller);
    viewPanel = new ArticleViewPanel();
    byCategoryPanel = new ArticlesByCategoryPanel();
    statsPanel = new StatsPanel();

    // “Πάντρεμα” στα tabs
    tabSearch.setLayout(new java.awt.BorderLayout());
    tabSearch.add(searchPanel, java.awt.BorderLayout.CENTER);

    tabView.setLayout(new java.awt.BorderLayout());
    tabView.add(viewPanel, java.awt.BorderLayout.CENTER);

    tabByCategory.setLayout(new java.awt.BorderLayout());
    tabByCategory.add(byCategoryPanel, java.awt.BorderLayout.CENTER);

    tabStats.setLayout(new java.awt.BorderLayout());
    tabStats.add(statsPanel, java.awt.BorderLayout.CENTER);

    // Refresh
    tabSearch.revalidate(); tabSearch.repaint();
    tabView.revalidate(); tabView.repaint();
    tabByCategory.revalidate(); tabByCategory.repaint();
    tabStats.revalidate(); tabStats.repaint();
}

    private void loadCategoriesAsync() {
        new javax.swing.SwingWorker<java.util.List<Category>, Void>() {

        @Override
        protected java.util.List<Category> doInBackground() {
        return grabCategories();
        }

        @Override
        protected void done() {
                try {
                    categoriesList = get(); // αποθήκευση στο field

                    // TODO: όταν παντρέψεις τα panels, εδώ θα καλέσεις updateCategories(...)
                    // articleViewPanel.updateCategories(categoriesList);
                    // articlesByCategoryPanel.updateCategories(categoriesList);

                } catch (Exception ex) {
                    javax.swing.JOptionPane.showMessageDialog(
                            MainFrame.this,
                            "Αποτυχία φόρτωσης κατηγοριών: " + ex.getMessage(),
                            "DB Error",
                            javax.swing.JOptionPane.ERROR_MESSAGE
                    );
                }
            }

        }.execute();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainFrameTabbedPanel = new javax.swing.JTabbedPane();
        tabSearch = new javax.swing.JPanel();
        tabView = new javax.swing.JPanel();
        tabByCategory = new javax.swing.JPanel();
        tabStats = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wiki Viewer App");

        javax.swing.GroupLayout tabSearchLayout = new javax.swing.GroupLayout(tabSearch);
        tabSearch.setLayout(tabSearchLayout);
        tabSearchLayout.setHorizontalGroup(
            tabSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1031, Short.MAX_VALUE)
        );
        tabSearchLayout.setVerticalGroup(
            tabSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );

        mainFrameTabbedPanel.addTab("Αναζήτηση Άρθρων", tabSearch);

        javax.swing.GroupLayout tabViewLayout = new javax.swing.GroupLayout(tabView);
        tabView.setLayout(tabViewLayout);
        tabViewLayout.setHorizontalGroup(
            tabViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1031, Short.MAX_VALUE)
        );
        tabViewLayout.setVerticalGroup(
            tabViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );

        mainFrameTabbedPanel.addTab("Προβολή άρθρου", tabView);

        javax.swing.GroupLayout tabByCategoryLayout = new javax.swing.GroupLayout(tabByCategory);
        tabByCategory.setLayout(tabByCategoryLayout);
        tabByCategoryLayout.setHorizontalGroup(
            tabByCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1031, Short.MAX_VALUE)
        );
        tabByCategoryLayout.setVerticalGroup(
            tabByCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );

        mainFrameTabbedPanel.addTab("Άρθρα ανά κατηγορία", tabByCategory);

        javax.swing.GroupLayout tabStatsLayout = new javax.swing.GroupLayout(tabStats);
        tabStats.setLayout(tabStatsLayout);
        tabStatsLayout.setHorizontalGroup(
            tabStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1031, Short.MAX_VALUE)
        );
        tabStatsLayout.setVerticalGroup(
            tabStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );

        mainFrameTabbedPanel.addTab("Στατιστικά & Λέξεις-κλειδιά", tabStats);

        getContentPane().add(mainFrameTabbedPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }
    
    public void updateViewAndSwitch(String title) {
        viewPanel.showArticle(title);
        mainFrameTabbedPanel.setSelectedIndex(1);
    }
    
    public static List<Category> grabCategories() {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("EapWikiPU");
        EntityManager em = emf.createEntityManager();
        try {
            Query findAllCategories = em.createNamedQuery("Category.findAll");

            List<Category> categoryList = findAllCategories.getResultList();
            for (Category c : categoryList) {
                System.out.println(c);
            }
            return categoryList;
        } catch (Exception e) {
            e.printStackTrace();
            return new ArrayList<>();
        } finally {
            System.out.println("GRABBED CATEGORIES, SUPPOSEDLY");
            em.close();
            emf.close();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane mainFrameTabbedPanel;
    private javax.swing.JPanel tabByCategory;
    private javax.swing.JPanel tabSearch;
    private javax.swing.JPanel tabStats;
    private javax.swing.JPanel tabView;
    // End of variables declaration//GEN-END:variables
}
