/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UITest;
import static com.plh24.packageAPI.APIMain.parseAndPrintResults;
import static com.plh24.packageAPI.APIMain.parsearticlefetch;
import UITest.ViewPanel;
import static com.plh24.packageAPI.APIMain.stripSnippetHTMLTags;
import com.plh24.packageAPI.WikiApiClient;
import java.io.IOException;
import org.json.JSONArray;
import org.json.JSONObject;
import java.awt.Color;

/**
 *
 * @author Equinox
 */
public class SearchPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchPanel
     */
    public SearchPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchInputField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchResultOutput = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        titleComboBox = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setText("Αναζήτηση:");

        searchInputField.setForeground(new java.awt.Color(153, 153, 153));
        searchInputField.setText("Αναζήτηση Εδώ");
        searchInputField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchInputFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchInputFieldFocusLost(evt);
            }
        });

        jButton1.setText("Αναζήτηση");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        searchResultOutput.setEditable(false);
        searchResultOutput.setFocusable(false);
        jScrollPane1.setViewportView(searchResultOutput);

        jLabel2.setText("Αποτελέσματα:");

        jLabel3.setText("Επιλογή Άρθρου:");

        titleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Επιλέξτε ---" }));

        jButton2.setText("Προβολή Άρθρου");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Αποθήκευση Άρθρου");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(searchInputField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String input = searchInputField.getText();
        WikiApiClient api = new WikiApiClient();
        try {
            String jsonResponse = api.searchWikipedia(input);
            System.out.println("--- Raw JSON Response ---");
            System.out.println(jsonResponse);
            System.out.println("--------------------------\n");
            JSONObject obj = new JSONObject(jsonResponse);
            JSONObject query = obj.getJSONObject("query");
            JSONArray searchResults = query.getJSONArray("search");

            System.out.println("Αποτελέσματα Αναζήτησης:");
            String output = "";
            for (int i = 0; i < searchResults.length(); i++) {
                JSONObject item = searchResults.getJSONObject(i);
                String title = item.getString("title");
                int wordCount = item.getInt("wordcount");
                titleComboBox.addItem(title);
                output += (i + 1) + ". " + title + " (" + wordCount + " λέξεις)";
                System.out.println((i + 1) + ". " + title + " (" + wordCount + " λέξεις)");
                output += "\n\tΤμήμα που ταιριάζει με την αναζήτηση: \"..." + stripSnippetHTMLTags(item.getString("snippet")) + "...\"";
                System.out.println("\tΤμήμα που ταιριάζει με την αναζήτηση: \"..." + stripSnippetHTMLTags(item.getString("snippet")) + "...\"");
                output += "\n\n";
            }
            searchResultOutput.setText(output);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String selectedTitle = titleComboBox.getSelectedItem().toString();
//        javax.swing.JTabbedPane tabbedPanel = (javax.swing.JTabbedPane) this.getParent().getParent();
//        tabbedPanel.setSelectedIndex(1);
        UITestFrame mf = (UITestFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        mf.updateViewAndSwitch(selectedTitle);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchInputFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchInputFieldFocusGained
        // TODO add your handling code here:
        if (searchInputField.getText().equals("Αναζήτηση Εδώ")){
            searchInputField.setText("");
            searchInputField.setForeground(new Color (0,0,0));
        }
    }//GEN-LAST:event_searchInputFieldFocusGained

    private void searchInputFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchInputFieldFocusLost
        // TODO add your handling code here:
        if (searchInputField.getText().equals("")){
            searchInputField.setText("Αναζήτηση Εδώ");
            searchInputField.setForeground(new Color (153,153,153));
        }
            
    }//GEN-LAST:event_searchInputFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchInputField;
    private javax.swing.JTextPane searchResultOutput;
    private javax.swing.JComboBox<String> titleComboBox;
    // End of variables declaration//GEN-END:variables
}
