/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UITest;
import com.plh24.packageEntities.Entities.Category;

/**
 *
 * @author Equinox
 */
public class UITestFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UITestFrame.class.getName());

    /**
     * Creates new form UITestFrame
     */
    public UITestFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        mainFrameTabbedPanel = new javax.swing.JTabbedPane();
        searchPanel1 = new UITest.SearchPanel();
        searchPanel2 = new UITest.SearchPanel();
        viewPanel1 = new UITest.ViewPanel();
        viewByCategoryPanel1 = new UITest.ViewByCategoryPanel();
        viewByCategoryPanel2 = new UITest.ViewByCategoryPanel();
        statisticsPanel1 = new UITest.StatisticsPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewPanel2 = new UITest.ViewPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainFrameTabbedPanel.setAutoscrolls(true);

        javax.swing.GroupLayout searchPanel1Layout = new javax.swing.GroupLayout(searchPanel1);
        searchPanel1.setLayout(searchPanel1Layout);
        searchPanel1Layout.setHorizontalGroup(
            searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        searchPanel1Layout.setVerticalGroup(
            searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanel1Layout.createSequentialGroup()
                .addComponent(searchPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 87, Short.MAX_VALUE))
        );

        mainFrameTabbedPanel.addTab("Αναζήτηση", searchPanel1);
        mainFrameTabbedPanel.addTab("Προβολή", viewPanel1);

        javax.swing.GroupLayout viewByCategoryPanel1Layout = new javax.swing.GroupLayout(viewByCategoryPanel1);
        viewByCategoryPanel1.setLayout(viewByCategoryPanel1Layout);
        viewByCategoryPanel1Layout.setHorizontalGroup(
            viewByCategoryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewByCategoryPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewByCategoryPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        viewByCategoryPanel1Layout.setVerticalGroup(
            viewByCategoryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewByCategoryPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewByCategoryPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        mainFrameTabbedPanel.addTab("Προβολή Ανά Κατηγορία", viewByCategoryPanel1);

        javax.swing.GroupLayout statisticsPanel1Layout = new javax.swing.GroupLayout(statisticsPanel1);
        statisticsPanel1.setLayout(statisticsPanel1Layout);
        statisticsPanel1Layout.setHorizontalGroup(
            statisticsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1094, Short.MAX_VALUE)
        );
        statisticsPanel1Layout.setVerticalGroup(
            statisticsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        mainFrameTabbedPanel.addTab("Στατιστικά", statisticsPanel1);

        jScrollPane1.setViewportView(viewPanel2);

        mainFrameTabbedPanel.addTab("tab5", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainFrameTabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1094, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainFrameTabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UITestFrame().setVisible(true));
        updateCategoriesComboBox();
    }
    
    public void updateViewAndSwitch(String title) {
        viewPanel1.showArticle(title);
        mainFrameTabbedPanel.setSelectedIndex(1);
    }
    
    public static void updateCategoriesComboBox() {
        System.out.println("UPDATED CATEGORIES, SUPPOSEDLY");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane mainFrameTabbedPanel;
    private UITest.SearchPanel searchPanel1;
    private UITest.SearchPanel searchPanel2;
    private UITest.StatisticsPanel statisticsPanel1;
    private UITest.ViewByCategoryPanel viewByCategoryPanel1;
    private UITest.ViewByCategoryPanel viewByCategoryPanel2;
    private UITest.ViewPanel viewPanel1;
    private UITest.ViewPanel viewPanel2;
    // End of variables declaration//GEN-END:variables
}
