/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UITest;

/**
 *
 * @author Equinox
 */
public class ViewByCategoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewByCategoryPanel
     */
    public ViewByCategoryPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        categorySearchBox = new javax.swing.JComboBox<>();
        showCategoryArticlesBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        articleTitleByCategory = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("Κατηγορίες");

        categorySearchBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ψευτοκατηγορία 1", "Ψευτοκατηγορία 2", "Ψευτοκατηγορία 3", "Ψευτοκατηγορία 4" }));

        showCategoryArticlesBtn.setText("Εμφάνιση Άρθρων");
        showCategoryArticlesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCategoryArticlesBtnActionPerformed(evt);
            }
        });

        articleTitleByCategory.setEditable(false);
        articleTitleByCategory.setFocusable(false);
        jScrollPane1.setViewportView(articleTitleByCategory);

        jLabel2.setText("Τίτλοι Άρθρων Ανά Κατηγορία");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(showCategoryArticlesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categorySearchBox, 0, 212, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 392, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(categorySearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(showCategoryArticlesBtn)
                        .addContainerGap(364, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showCategoryArticlesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCategoryArticlesBtnActionPerformed
        // TODO add your handling code here:
        System.out.println("ΝΟΜΙΖΕΣ ΘΑ ΕΜΦΑΝΙΖΩ ΑΡΘΡΑ Ε? ΟΥΤΕ ΚΑΝ");
        String selectedCategory = categorySearchBox.getSelectedItem().toString();
        articleTitleByCategory.setText("Ο ΧΡΗΣΤΗΣ ΔΙΑΛΕΞΕ: " + selectedCategory + "\nΕΜΦΑΝΙΖΩ ΑΡΘΡΑ ΚΑΙ ΚΑΛΑ\nΆρθρο 1\nΆρθρο 135");
    }//GEN-LAST:event_showCategoryArticlesBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane articleTitleByCategory;
    private javax.swing.JComboBox<String> categorySearchBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton showCategoryArticlesBtn;
    // End of variables declaration//GEN-END:variables
}
