/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UITest;
import static com.plh24.packageAPI.APIMain.parseAndPrintResults;
import static com.plh24.packageAPI.APIMain.parsearticlefetch;
import com.plh24.packageEntities.Category;
import com.plh24.packageAPI.WikiApiClient;
import java.io.IOException;
import org.json.JSONArray;
import org.json.JSONObject;
import java.util.ArrayList;
import java.util.List;
import java.awt.Color;
import javax.swing.JOptionPane;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import com.plh24.packageEntities.Category;
import com.plh24.packageEntities.Article;
import com.plh24.packageUtils.generalUtils;
import jakarta.persistence.Query;
/**
 *
 * @author Equinox
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    public ViewPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jPopupMenu5 = new javax.swing.JPopupMenu();
        jPopupMenu6 = new javax.swing.JPopupMenu();
        jPopupMenu7 = new javax.swing.JPopupMenu();
        saveArticleButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentsTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ratingComboBox = new javax.swing.JComboBox<>();
        articleTitle = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        articleBody = new javax.swing.JTextPane();

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        saveArticleButton.setText("Αποθήκευση");
        saveArticleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveArticleButtonActionPerformed(evt);
            }
        });

        commentsTextArea.setEditable(false);
        commentsTextArea.setBackground(new java.awt.Color(63, 63, 63));
        commentsTextArea.setColumns(20);
        commentsTextArea.setRows(5);
        commentsTextArea.setFocusable(false);
        jScrollPane1.setViewportView(commentsTextArea);

        jLabel1.setText("Σχόλια:");

        jLabel2.setText("Κατηγορία:");

        jLabel3.setText("Βαθμολογία:");

        ratingComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1/5 ★", "2/5 ★★", "3/5 ★★★", "4/5 ★★★★", "5/5 ★★★★★" }));

        articleTitle.setText("Τίτλος");

        articleBody.setEditable(false);
        articleBody.setFocusable(false);
        jScrollPane3.setViewportView(articleBody);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(categoryComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ratingComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1))
                    .addComponent(saveArticleButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(articleTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(articleTitle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(ratingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveArticleButton)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveArticleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveArticleButtonActionPerformed
        // TODO add your handling code here:
        if (articleTitle.getText().equals("Τίτλος")){
            JOptionPane.showMessageDialog(this,
                    "Δεν έχετε προβάλλει κάποιο άρθρο για αποθήκευση!",
                    "Δεν υπάρχει άρθρο.",
                    JOptionPane.WARNING_MESSAGE
                    );
            return;
        }
        String title = articleTitle.getText();
        int rating = ratingComboBox.getSelectedIndex() + 1;
        String category = categoryComboBox.getSelectedItem().toString();
        String comments = commentsTextArea.getText();
        generalUtils.saveArticle(title, rating, category, comments);
        
    }//GEN-LAST:event_saveArticleButtonActionPerformed

    public void showArticle(String title) {
        WikiApiClient api = new WikiApiClient();
        try {
            String jsonResponse = api.fetchArticle(title);
            JSONObject obj = new JSONObject(jsonResponse);
            JSONObject query = obj.getJSONObject("query");
            JSONArray pages = query.getJSONArray("pages");
            for (int i = 0; i < pages.length(); i++) {
                JSONObject page = pages.getJSONObject(i);
                if (!page.has("extract")) continue;
                String cleanText = page.getString("extract");
                articleTitle.setText(title);
                articleBody.setText(cleanText);
                commentsTextArea.setEditable(true);
                commentsTextArea.setFocusable(true);
                commentsTextArea.setBackground(new Color (255,255,255));
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    public void updateCategories(List<Category> categories){
        for (Category c : categories) {
            categoryComboBox.addItem(c.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane articleBody;
    private javax.swing.JLabel articleTitle;
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JTextArea commentsTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JPopupMenu jPopupMenu5;
    private javax.swing.JPopupMenu jPopupMenu6;
    private javax.swing.JPopupMenu jPopupMenu7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private javax.swing.JComboBox<String> ratingComboBox;
    private javax.swing.JButton saveArticleButton;
    // End of variables declaration//GEN-END:variables
}
